### ISSUE TITLE
Implement base64 as separate module

### ISSUE THREAD

**Issue by ianwremmel** [cisco/node-jose#10]
There are some parts of an sdk you may be familiar with that only need to depend on node-jose because of the base64 utilities. Can these base moved to a separate module?

**Comment by linuxwolf** [comment]
How about we replace the internal jose.util.base64url with https://github.com/brianloveswords/base64url ?

**Comment by ianwremmel** [comment]
works for me

**Comment by linuxwolf** [comment]
I'll run some tests and see if it's a suitable replacement.  From looking at the source, it looks like it'll be a simple drop-in.

**Comment by linuxwolf** [comment]
The bad news is base64url is not a drop-in replacement.  The closest it gets is to always return a Buffer.

That's fine for node-jose, but it's a breaking change to its published API.

**Comment by ianwremmel** [comment]
Can the logic in node-jose be a light wrapper around [base64.fromBase64](https://github.com/brianloveswords/base64url#base64urlfrombase64b64encodedstring) and [base64url.toBase64](https://github.com/brianloveswords/base64url#base64urltobase64b64urlencodedstring)? That would let use keep the node-jose api the same while I could just the methods I need from base64url directly.

**Comment by ianwremmel** [comment]
Though, that still means that clients that don't need Buffers for anything else will end up browserifying the entire Buffer shim.

**Comment by linuxwolf** [comment]
clients are going to browserify the entire Buffer shim anyway.  All the rest of the API expects Buffers.

**Comment by ianwremmel** [comment]
My motivation here was that there are going to be some sdk variants that don't need to support encryption (and therefore, won't need Buffers) but will need base64url support. Right now, the core sdk has a dependency on node-jose which isn't ideal.

**Comment by linuxwolf** [comment]
See PR #11.  Still need to test against node-scr and node-kms, but I think this solves your concern.

**Comment by ianwremmel** [comment]
works for me. thanks!
