### ISSUE TITLE
Version 0.8.0 broken, due to change in underlying node-forge Git repo

### ISSUE THREAD

**Issue by mamendoz** [cisco/node-jose#100]
The package.json of node-jose@0.8.0 unfortunately has hardcoded Git URL links in in the dependency list.

```json
"dependencies": {
    "es6-promise": "^3.1.2",
    "jsbn": "git+https://github.com/andyperlitch/jsbn.git",
    "lodash.assign": "^4.0.8",
    "lodash.clone": "^4.3.2",
    "lodash.fill": "^3.2.2",
    "lodash.flatten": "^4.2.0",
    "lodash.intersection": "^4.1.2",
    "lodash.merge": "^4.3.5",
    "lodash.omit": "^4.2.1",
    "lodash.partialright": "^4.1.3",
    "lodash.pick": "^4.2.0",
    "lodash.uniq": "^4.2.1",
    "long": "^3.1.0",
    "node-forge": "git+https://github.com/linuxwolf/forge.git#master",
    "urlsafe-base64": "git+https://github.com/linuxwolf/urlsafe-base64.git#encoding",
    "uuid": "^2.0.1"
  }
```

Because of this dependency, this version of the module is vulnerable to any changes that are made on the master branch from 

https://github.com/linuxwolf/forge/commits/master/.

Recently, the master branch was updated to reflect changes from the parent repo.

![image](https://cloud.githubusercontent.com/assets/12533535/24173857/1c4d037e-0e4b-11e7-94de-ed97c46b1b10.png)

Many of the files were moved from `js` directory to `lib` directory.

Because of this ... old versions that are using the git url are probably broken.

Simply doing `require('node-jose');`  throws an error.

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'node-forge/js/aes'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mamendoz/node_modules/node-jose/lib/deps/forge.js:9:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

```

I don't think it's possible to go back and overwrite a published module version in npm.js to fix this, but it's probably worth deprecating all those old versions. (https://docs.npmjs.com/cli/deprecate)

**Comment by linuxwolf** [comment]
It actually was possible to go back, at least for now (-:

Sorry for the inconvenience.
