### ISSUE TITLE
number typed "kid"

### ISSUE THREAD

**Issue by panva** [cisco/node-jose#109]
Hello @linuxwolf, a user of my openid-client library has come across an issue that i was able to track down to node-jose (sort of).

The issue is shown below

```js
JWK.store.KeyStore.asKeyStore({
  keys: [
    {
       kty: 'RSA',
       alg: 'RS256',
       use: 'sig',
       n: 'zi9ox5mVK1nS6rASj5VwTqsozmyoHcqOuf2LLvuNzijPx7ybASzUerP-QZCYL3EC66TtmO2T2fxEyfrK0r7OpsJ3QYlZZ4rHm7s_mFc9upxjnTZ-ElJJsAxWhuBZyZTpzfXT7lTm4QN0QZgy3ydmv4W4RFh2tzAZ4wKc4ruoI-SIVSiZZZ_R3-zhu6zu2JfRc6Vt6MapLfgNtaVuzKWeuCC-42-4vngf2TYqJLlRvrywNJ1qtf-dUpB5UutJUIPBeDrVmoJPC7H8cdbOxSV3b4y8cvn0aQQouO3vQGyNg-LA0D-NGuSW-nEOyfuUR0skcUh6VIhEpcw8iF8nJ1X7yQ',
       e: 'AQAB',
       kid: 1
     }
  ]
}).then(function (keystore) {
  console.log(keystore.get()); // => JWKBaseKeyObject {
    // keystore: JWKStore {},
    // length: 2048,
    // kty: 'RSA',
    // kid: 1,
    // use: 'sig',
    // alg: 'RS256' }

  console.log(keystore.get({ kid: 1 }); // => null
  console.log(keystore.get({ kid: '1' }); // => returns the key
});
```

Essentially at blame is an openid connect provider releasing jwks with a number `kid` claim, even though it should be a case-sensitive string. However, node-jose does track the value as a number (as seen by the first console.log), but only returns the key using `get()/all()` when a string `kid` is passed in.

What is your take on this?

**Comment by linuxwolf** [comment]
Mr initial thought is this is a bug in node-jose wht it accepted an invalid `kid` value type.  I could also see this being coerced into a string during import.

**Comment by panva** [comment]
coersing to string during import is one thing will not necessarily solve the issue when i receive an id token and use it's header as input to get() or all(), so would also have to coerse it for those methods, and who knows what other consequences it could have...

Since node-jose finds the right key so long as the input is string, how about doing just that? coersing the input to `all` and `get`

**Comment by linuxwolf** [comment]
Sorry for the delays.

I can start with that coersion.  I am concerned about pushing out bad protocol, but this seems like a reasonable start that doesn't prevent better from happening in the future.

If you have a PR, please submit it.  Otherwise I'll try to get to this over the next few days.

**Comment by panva** [comment]
I will open a PR in the coming days.
