### ISSUE TITLE
Decryption Failed

### ISSUE THREAD

**Issue by obengwilliam** [cisco/node-jose#118]
nodejs version : 7.7.4
node-jose version: 0.9.4
## Error 
```
Error: decryption failed
    at nodejs (/Users/mac/dev/current/api/node_modules/node-jose/lib/algorithms/aes-gcm.js:315:13)
    at main (/Users/mac/dev/current/api/node_modules/node-jose/lib/algorithms/helpers.js:113:42)
    at Object.exports.decrypt (/Users/mac/dev/current/api/node_modules/node-jose/lib/algorithms/index.js:109:10)
    at JWKBaseKeyObject.value (/Users/mac/dev/current/api/node_modules/node-jose/lib/jwk/basekey.js:605:25)
    at /Users/mac/dev/current/api/node_modules/node-jose/lib/jwe/decrypt.js:257:27
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
```

## How to reproduce error?
```
const makeKeyJWE = store.generate('oct', 256, {
    kid: kid,
    alg: 'A256GCM',
    use: 'enc'
  })

makeJWE = function (props) {
    return makeKeyJWE.then(function (key) {
      const input = Buffer.from(JSON.stringify(props))
      return jose.JWE.createEncrypt({format: 'compact'}, key)
            .update(input).final()
    })
  }

  verifyJWE = function (token) {
    return jose.JWE.createDecrypt(store).decrypt(token)
        .then(function (result) {
          return JSON.parse(result.payload.toString())
        })
  }
```
## To create a token 
TokenEngine.makeJWE({iss: 'api.k.com', aud: 're3434343ddr34ddfdfdffsd'})
  .then(token => {
    console.log(token)
  })

## To decrypt this token
TokenEngine.verifyJWE(TOKEN_GOES_HERE)
  .then(details => {
    console.log(details)
  })
  .catch(err => {
    console.error(err)
  })
 
Now, when I try to decrypt the token that is when I receive the above error. I cant seem to find what is causing it.
:)

**Comment by linuxwolf** [comment]
Is this reproducible if `makeJWE` and `verifyJWE` are called from the same script without restarting the script? (e.g., a trivial "verify what's generated" type of script that encrypts then immediately decrypts.)

Would it be possible to provide a sample output of `makeJWE`, and possibly of the key used for that `makeJWE` call?

The most common reasons for "decryption failed" are:
1. the key used to encrypt is different from the key used to decrypt
2. the tag is missing or corrupted

I suspect you're running into option 1.  From the sample, it appears `kid` is defined separately, somewhere.  Without more context, it would appear possible that a new key value is generated for the same `kid`, which would certainly lead to option 1 occurring.

If you don't have a particular reason to specify the kid, I would recommended using the default kid generation, which is the SHA-1 thumbprint of the symmetric key.

**Comment by obengwilliam** [comment]
ok. That is fine.
Would it be possible to provide a sample output of makeJWE, and possibly of the key used for that makeJWE call?

eyJhbGciOiJkaXIiLCJraWQiOiJma2FqaGZreWdramhhZ2pkaGdfaWl4bWZsa3pxbHAiLCJlbmMiOiJBMjU2R0NNIn0..vAvuK8k2VyLQLbNR.au1SEr20qFvbOnpuM2jRd7lpjV0WqaW3ci_PVMIl_Paui89Qu9fLa6xZUjcoNMXNwlax4pIdsA.Dz84mJhGBwdm6PyJfg0R-w

## Without more context, it would appear possible that a new key value is generated for the same kid, which would certainly lead to option 1 occurring.
store.generate('oct', 256, {
    kid: 'fkajhfkygkjhagjdhg_iixmflkzqlp',
    alg: 'A256GCM',
    use: 'enc'
  })
How do I prevent a new key from being generated? I thought the key will always remain the same given the same details.

# 
If you don't have a particular reason to specify the kid, I would recommended using the default kid generation, which is the SHA-1 thumbprint of the symmetric key.
Tried using that like this

store.generate('oct', 256, {
    kid: 'fkajhfkygkjhagjdhg_iixmflkzqlp',
    alg: 'A256GCM',
    use: 'enc'
  })

**Comment by linuxwolf** [comment]
> How do I prevent a new key from being generated? I thought the key will always remain the same given the same details.

`generate()` always creates a new key -- none of the values, other than length, are factored into the generation of the key's `k` value (they are used for the key's "metadata").  You could instead call `add()` with the JWK representation of your symmetric key.  For prototyping purposes, you could embed it in the code, but you'll likely want to read the JWK from a carefully-managed file or the environment variables in production.

Assing `jwk` is the following:
```
const DEV_JWK = {
  "kty": "oct",
  "kid": "t1YSLFyfd9BwKVLr1vH0QPDccZcBS-NSJkqze6R7PDA",
  "use": "enc",
  "alg": "A256GCM",
  "k": "0hsk-ETkH2QQNjkkhyPSi4rG--oWT8wCHgsqa6WtxZo"
};

// read something from the environment or filesystem for production!
var jwk = DEV_JWK;
```
Then you can import it using `add` (which returns a promise for the jose.JWK instance):

```
var makeJWK = store.add(jwk);
```

**Comment by obengwilliam** [comment]
@linuxwolf thank you

**Comment by rustyro** [comment]
6 years later and this is the only thing I could find on the internet that saved me after hours of search. @linuxwolf it might be worth adding to the docs expressly that a new `JWK` always gets generated regardless of using the same `kid`.
