### ISSUE TITLE
Unable to create JWE in Safari v10.1.2

### ISSUE THREAD

**Issue by graysoncl** [cisco/node-jose#123]
Hello,

It appears that creating JWE's doesn't work in Safari v10.1.2. The following code works (and successfully returns a JWE) in every other browser including Safari v10.1.1:

`const key = await keystore.add(PUBLIC_KEY, 'pem');

return await jose.JWE.createEncrypt({format: 'compact', alg: 'RS256'}, key).update(payload).final();`

After upgrading to Safari v10.1.2, however, the final() method returns a rejected promise with the result: "TypeError: Type error". 

Thank you for looking into this.

**Comment by linuxwolf** [comment]
First, note that "RS256" is not a valid JWE key encryption algorithm.  I'm going to assume it was "RSA-OAEP".

Looking at https://peculiarventures.github.io/pv-webcrypto-tests/ as a benchmark, it appears that most of the algorithms that would have been used here are failing.  I remember running these on Safari 10.0 with far fewer errors, so it appears to me to be a regression.

There are fallback routines that can be used, but the core logic needs to be changed to enable these.

**Comment by graysoncl** [comment]
I see, thanks for the heads up. 

I'm using now 'RSA-OAEP' as the encryption algorithm and it works everywhere apart from Safari.

Any suggestions for a workaround?

**Comment by linuxwolf** [comment]
PR #125 is meant to address this, although it's a little heavy-handed.  It passed Travis/SauceLabs and it "works on my machine" (Safari 10.1.2), so this will be the next patch version (before tomorrow USA times).

In meantime, you could change your install to point to this repo's master branch.

**Comment by graysoncl** [comment]
Sounds good. Thanks again!
