### ISSUE TITLE
Enhancement: support RSA-PSS with WebCryptoAPI

### ISSUE THREAD

**Issue by rriemann** [cisco/node-jose#128]
As far as I can test with https://diafygi.github.io/webcrypto-examples/, at least Firefox supports now RSA-PSS.

Hence, the note here is no longer true?

https://github.com/cisco/node-jose/blob/0d1a8cdc351988d74ac42398c3d973902db3d808/lib/algorithms/rsassa.js#L157-L159

I plan to use this scheme to implement blind signatures.

**Comment by linuxwolf** [comment]
It is true that comment no longer applies.  Not sure when a WebCrypto API variant will be implemented here, but the current still works (albeit slowly).
