### ISSUE TITLE
JWT profiles validation and API, library listings

### ISSUE THREAD

**Issue by panva** [cisco/node-jose#131]
node-jose is the most feature complete JS library. With Asymmetrical and Symmetrical Signing and Encryption support covering the full JOSE family of specifications and algorithms it stands above all others in terms of completeness.

Having to only code the ID Token claim validations myself node-jose enabled me to provide openid RP and OP libraries with all of the above supported. Thank you!

And yet, node-jose is missing its listing in places such as

- https://openid.net/developers/jwt/
- https://jwt.io/

If common JWT profiles / claim validations API was included there's no reason not to be listed in both.

Profiles such as OIDC ID Token, OIDC Logout Token, JWT Request (OAuth2.0 and OIDC), SET share a lot, would you be open to have an API such as `jose.JWT.IDToken` or just `jose.IDToken` wrapping the common tasks and validations for these JWT profiles?

**Comment by linuxwolf** [comment]
We'd not be opposed to better JWT support.  However, significant care would need to be applied to certain configurations; for example, any support for `"alg":"none"` needs to be very deliberate on the part of the library user.

My preference would be for something under `jose.JWT`.

**Comment by panva** [comment]
Alright, i'll try to do my best and open a PR then. Thank you for your thoughts.
