### ISSUE TITLE
question: for JWE createEncrypt : how to make the  private key not change every time?

### ISSUE THREAD

**Issue by HeMiJack888** [cisco/node-jose#132]
this is my code:

const props = {
	//kid = "3f7b122d-e9d2-4ff7-bdeb-a1487063d799",
	x:"ufQkXr3L841ATLhZ4rQ4e--udQtLWawOxmjVjg88Y8Q",
	y:"mEfxmKOAIqlEo9oAWpI8KUk82G7xh_2BOfTglU5GPsske",
    use: "enc",
    //alg: "ECDH"
	};
	const key = await jose.JWK.createKeyStore().generate("EC","P-256",props);

	const final = await jose.JWE.createEncrypt({
		formate: 'compact',
		protect:false,
		fields:{cty:'application/hal+json'},
	},{reference:'jwk',key})
	.update(JSON.stringify("Gambling is illegal at Bushwood sir, and I never slice."))
	.final();
	
	//const verified = !!await jose.JWE.createDecrypt(key).verify(final).catch(()=>{});
	console.log('EC');
	console.log(JSON.stringify(final,null,4));
	//console.log('verified:', verified);
	console.log(key.toJSON(true));

I want to make the private key the same for everytime, so I make the props for x:"ufQkXr3L841ATLhZ4rQ4e--udQtLWawOxmjVjg88Y8Q",
y:"mEfxmKOAIqlEo9oAWpI8KUk82G7xh_2BOfTglU5GPsske",

but finally, the x and y of props do not make effect, everytime I run the code, I get different x and y, and the different private key!!!

my result:
result1:
{ kty: 'EC',
  kid: 'EXdpviIzwPNscQC_qQetj75SQ3rvvFV4N-vns64OdNs',
  use: 'enc',
  x: 'r3z9HIz2MqEbjlL9ui22vuv4OvJITzJ3TcG7Fz_d1Qo',
  y: 'TZQUGUtNKqFt4So0crFXiY7Qree7GH_kqSBREShREHg',
  crv: 'P-256',
  d: '6kAN5zyv4QCotcwut82EgtlGPAhtslt1s_bG6APgZBA' }

result2:
{ kty: 'EC',
  kid: 'azNuys3mrwsKy6GATLM2913UG_gwrhbIC7ux7-tJYbA',
  use: 'enc',
  x: 'dmMJprXD6IjqHimyyrLXOjzcMV0KGOc0gHojTMnbLyY',
  y: '67uTFTkv2USxfaRvNz6fCHqUjHBNZ2HuFGu-140XOOc',
  crv: 'P-256',
  d: '6XB0NJADtaBxoF2CUTIrPENOcAsrct4qWiM4kTzLB08' }

the x and y in result1 and result2 are not the ones I have set!

**Comment by linuxwolf** [comment]
Use `jose.JWK.asKey(props)` instead of `.generate()`.

The former function will turn `props` into a `jose.JWK.Key` object, while the latter function creates a new keying material each time it's called.
