### ISSUE TITLE
alg A128GCMKW encryption/decryption doesn't work

### ISSUE THREAD

**Issue by panva** [cisco/node-jose#133]
Hello @linuxwolf, 

i'm unable to get `A128GCMKW` alg compact JWE to work. Not sure if there's something obvious i'm doing wrong, i would appreciate your help. Should I be including `tag` and `iv` in the header(fields)? It encrypts without `tag` just fine. But i cannot get decrypt to work, even with the same key(store) as shown below.

```js
const jose = require('node-jose');
const format = 'compact';
const clientKS = jose.JWK.createKeyStore();
const secret = 'GfsT479VMy5ZZZPquadPbN3wKzaFGYo1CTkb0IFFzDNODLEAuC2GUV3QsTye3xNQ';
const alg = 'A128GCMKW';
const base64url = require('base64url');
const crypto = require('crypto');
const payload = JSON.stringify({ foo: 'bar' });
const fields = { alg };

const bufferderived = crypto.createHash('sha256')
      .update(secret)
      .digest()
      .slice(0, 128 / 8);

clientKS.add({
  k: base64url(bufferderived), kty: 'oct',
}).then(() => {
  fields.iv = base64url(crypto.randomBytes(12)); // doesn't encrypt without iv
  fields.tag = base64url(crypto.randomBytes(16)); // does encrypt without tag
  return jose.JWE.createEncrypt({ format, fields }, { key: clientKS.get(), reference: false })
    .update(payload)
    .final();
}).then((crypted) => {
  console.log(crypted)
  return jose.JWE.createDecrypt(clientKS.get()).decrypt(crypted);
}).then(console.log)

// > Error: no key found
```

**Comment by linuxwolf** [comment]
It should be generating the `iv` and `tag` to insert into the fields.; that you have to provide them is clearly a bug and the `decrypt` error is likely very rooted to that.

Unfortunately, the fix is non-trivial and I don't see a workaround.  I don't have an ETA on that fix, yet.

**Comment by panva** [comment]
just for completeness, `p2s` and `p2a` i also have to provide for PBES2

**Comment by linuxwolf** [comment]
The latter (`p2c` and `p2s`) I expect, and is more an inconvenience than an outright error.

**Comment by panva** [comment]
roger for p2c and p2s, got those figured long ago. 

Thanks for looking into A***GCMKW, any way i can be of help please just let me know.

**Comment by linuxwolf** [comment]
The encryption needs to be tweaked to allow for some outgoing configuration.  My first thought would be to better distinguish JWKKey's `wrap`/`unwrap` from `encrypt`/`decrypt` (on the internals), with the former optionally providing the new heading fields, and the latter looking at header fields.

**Comment by panva** [comment]
I fear my knowledge of both the node-jose internals and the actual algorithms is not good enough to be able to help with such refactoring. Sorry

**Comment by panva** [comment]
Hello @linuxwolf I wonder if the mentioned alg support should be outright removed for now since there's no way to use them.

**Comment by linuxwolf** [comment]
That is probably the best approach to take.

I'm hesitant to complete remove the algorithm logic, but:

* `JWKKey.algoritms()` should not include any A*GCMKW algorithms
* `JWKKey.supports()` should always return `false` if asked about any A*GCMKW algorithms

**Comment by panva** [comment]
Turns out that's not a trivial task either since many tests use A*GCMKW

**Comment by linuxwolf** [comment]
I just took a look through the tests (again).  It looks like all the A*GCMKW use is restricted to `test/jwk/octkey-test.js`, which at least puts it all in one place.

Whatever makes sense to change those wrapKey/unwrapKey tests is fine.

**Comment by panva** [comment]
I'm not really sure what i'm doing, but with the exception of [octkey-test.js#L800-L816](https://github.com/cisco/node-jose/blob/master/test/jwk/octkey-test.js#L800-L816) this [commit](https://github.com/panva/node-jose/commit/46d0f794c3d34e4a7586d4dcd6fb0ab48ee82754) seems to do the trick. Please review thoroughly and see if you can figure the remaining failing test.

**Comment by linuxwolf** [comment]
@panva looks like a great start!  If you submit a PR, I'll see if I can help get that broken test sussed out.

My only issue in the removal of "A*GCMKW" from `aes-gcm` support, but otherwise like it!

**Comment by panva** [comment]
as i mentioned, not really sure what is supposed to be removed and what isn't. Maybe aes-gcm.js should be reverted and then other changes aren't needed.

**Comment by linuxwolf** [comment]
@panva I'd recommend you submit the PR as is, and we can work out the details from there
