### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by SimonSchick** [cisco/node-jose#135]
I was wondering if you are interested in supporting TypeScript as it makes using your library much easier.
We are using `node-jose` in a few places and created a _few_ typings for it that cover our use cases and wanted to contribute them.
They are rather incomplete but I hope you are willing to built on top of them:

```
// These typings are not 100% complete.

declare module 'node-jose' {
    export const JWA: {
        digest(): any;
        derive(): any;
        sign(): any;
        verify(): any;
        encrypt(): any;
        decrypt(): any;
    }

    export interface IJWEEncryptor {
        update (input: any): this;
        final(): Promise<string>;
    }

    export interface IJWEDecryptor {
        decrypt(input: string): Promise<IJWEDecryptResult>;
    }

    export interface IBaseResult {
        /**
         * the combined 'protected' and 'unprotected' header members
         */
        header: any;
        /**
         * the signed content
         */
        payload: Buffer;
        /**
         * The key used to verify the signature
         */
        key: IJWKKey;
    }

    export interface IJWEDecryptResult {
        /**
         * an array of the member names from the "protected" member
         */
        protected: string[];
        /**
         * the decrypted content (alternate)
         */
        plaintext: Buffer;
    }

    export const JWE: {
        createEncrypt(key: IJWKKey): IJWEEncryptor;
        createEncrypt(keys: IJWKKey[]): IJWEEncryptor;
        createEncrypt(options: {
            format?: 'compact' | 'flattened';
            zip?: boolean;


        }, key: IJWKKey): IJWEEncryptor;
        createDecrypt(key: IJWKKey): IJWEDecryptor;
    }

    export type KeyUse = 'sig' | 'enc' | 'desc';

    export interface IRawKey {
        alg: string;
        kty: string;
        use: KeyUse;

        // e and n make up the public key
        e: string;
        n: string;
    }

    export interface IKeyStoreGetFilter {
        kty?: string;
        use?: KeyUse;
        alg: string;
    }

    export interface IKeyStoreGetOptions extends IKeyStoreGetFilter {
        kid: string;
    }

    export interface IKeyStore {
        toJSON(exportPrivateKeys?: boolean): object;
        get (kid: string, filter?: IKeyStoreGetFilter): IRawKey;
        get (options: IKeyStoreGetOptions): IRawKey;
        all (options: Partial<IKeyStoreGetOptions>): IRawKey[];
        add (key: IRawKey): Promise<IJWKKey>;
        /**
         * @param key
         *  String serialization of a JSON JWK/(base64-encoded) PEM/(binary-encoded) DER
         *  Buffer of a JSON JWK/(base64-encoded) PEM/(binary-encoded) DER
         * @param form
         * is either a:
         * - "json" for a JSON stringified JWK
         * - "private" for a DER encoded 'raw' private key
         * - "pkcs8" for a DER encoded (unencrypted!) PKCS8 private key
         * - "public" for a DER encoded SPKI public key (alternate to 'spki')
         * - "spki" for a DER encoded SPKI public key
         * - "pkix" for a DER encoded PKIX X.509 certificate
         * - "x509" for a DER encoded PKIX X.509 certificate
         * - "pem" for a PEM encoded of PKCS8 / SPKI / PKIX
         */
        add (key: string | Buffer, form: 'json' | 'private' | 'pkcs8' | 'public' | 'spki' | 'pkix' | 'x509' | 'pem'): Promise<IJWKKey>;
        remove(key: IJWKKey)
    }

    export interface IJWKKey {
        /**
         * Defaults to false
         */
        toPEM(isPrivate?: boolean)
        keystore: IKeyStore;
        length: number;
        kty: string;
        kid: string;
        use: KeyUse;
        alg: string;
    }

    export const JWK: {
        isKeyStore(input: any): input is IKeyStore;
        isKey(input: any): input is IJWKKey;
        createKeyStore(): IKeyStore;
        asKeyStore(input: any): Promise<IKeyStore>;
        asKey (rawKey: IRawKey): Promise<IJWKKey>;
        /**
         * @param key
         *  String serialization of a JSON JWK/(base64-encoded) PEM/(binary-encoded) DER
         *  Buffer of a JSON JWK/(base64-encoded) PEM/(binary-encoded) DER
         * @param form
         * is either a:
         * - "json" for a JSON stringified JWK
         * - "private" for a DER encoded 'raw' private key
         * - "pkcs8" for a DER encoded (unencrypted!) PKCS8 private key
         * - "public" for a DER encoded SPKI public key (alternate to 'spki')
         * - "spki" for a DER encoded SPKI public key
         * - "pkix" for a DER encoded PKIX X.509 certificate
         * - "x509" for a DER encoded PKIX X.509 certificate
         * - "pem" for a PEM encoded of PKCS8 / SPKI / PKIX
         */
        asKey (key: string | Buffer, form: 'json' | 'private' | 'pkcs8' | 'public' | 'spki' | 'pkix' | 'x509' | 'pem'): Promise<IJWKKey>;
        MODE_SIGN: 'sign';
        MODE_VERIFY: 'verify';
        MODE_ENCRYPT: 'encrypt';
        MODE_DECRYPT: 'decrypt';
        MODE_WRAP: 'wrap';
        MODE_UNWRAP: 'wrap';
    }

    export interface IVerificationResult extends IBaseResult {
        /**
         * the verified signature
         */
        signature: Buffer;
    }

    export interface IJWSVerifier {
        verify (input: string): Promise<IVerificationResult>;
    }

    export const JWS: {
        /**
         * Using a keystore.
         */
        createVerify(keyStore: IKeyStore): IJWSVerifier;
        /**
         * To verify using an implied Key
         */
        createVerify(keyStore: IJWKKey): IJWSVerifier;
        /**
         * To verify using a key embedded in the JWS
         */
        createVerify(): IJWSVerifier;
    }

    export type TypedArray = Int8Arrar |
        Uint8Array |
        Uint8ClampedArray |
        Int16Array |
        Uint16Array |
        Int32Array |
        Uint32Array |
        Float32Array |
        Float64Array;

    export const util: {
        asBuffer (arr: ArrayBuffer | ArrayLike | TypedArray): Buffer;
        base64url: {
            encode(data: Buffer, encoding = 'utf8'): string;
            decode(str: string): Buffer;
        },
        utf8: {
            encode (str: string): string;
            decode (str: string): string;
        }
        randomBytes(size: number): Buffer;
    }

    export const parse: {
        (input: string | Buffer | object): object;
        compact (input: string): object;
        json (input: object): object;
    }
}
```

**Comment by linuxwolf** [comment]
Not opposed to typescript bindings, but TypeScript is not part of my flow.  I'd be worried about properly maintaining the bindings.

**Comment by SimonSchick** [comment]
Yea, it needs some investment but the payoff is that you effectively support a new language.

**Comment by HugoDF** [comment]
The typings would likely only need to change if you change the public API of the package.
VSCode supports typings out of the box (even for JS files) so this isn't just for TypeScript users.
The easiest way to maintain the typings up to date would probably be to use TypeScript but it's not necessary.
If you don't want to support the typings as part of this project, we could probably add them to https://github.com/DefinitelyTyped/DefinitelyTyped so that they're not your direct concern?

**Comment by linuxwolf** [comment]
Not opposed to supporting it, if there's a way to help do it in tests -- and without rewriting everything in TypeScript (-:

If you're willing to help @HugoDF / @SimonSchick the PRs would be greatly appreciated!

**Comment by HugoDF** [comment]
Actually the types are in definitely typed already, there's some gaps though see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15350.

**Comment by LiraNuna** [comment]
@HugoDF are you sure that's the case? it seems like the PR was merged but then reverted. When I try to install `@types/node-jose` npm 404s and I can't find the package in npm: https://www.npmjs.com/package/@types/node-jose

**Comment by HugoDF** [comment]
@LiraNuna Yeah true, I thought VSCode's Intellisense was using a typing from somewhere but actually it's just inferring from the JS in node_modules. I might have a stab at this this weekend.

**Comment by BorntraegerMarc** [comment]
@HugoDF Did you manage to make a new PR for typings? :)

**Comment by MaKleSoft** [comment]
Any updates on this? I would love to see "official" typings on DefinitelyTyped. Also, I would seriously consider porting the project to TypeScript altogether. If there is any domain where worrying about type safety is a good idea, it's probably crypto... Also, it's not like you need to "rewrite" the whole thing. TypeScript is a superset of JavaScript so you should be able to just add the type declarations without actually changing any of the logic. And you'll probably catch at least a few bugs while doing it.

**Comment by linuxwolf** [comment]
We're certainly open to a PR for this, but haven't had the engergy to do it ourselves.

**Comment by nadunindunil** [comment]
Did anyone find a method to overcome this issue? a temporary one may be. @SimonSchick  can you please give us a working example?

**Comment by SimonSchick** [comment]
I have not worked with this library in a while, sorry, you're on your own for now.

**Comment by nadunindunil** [comment]
hi @SimonSchick , 
I would like to contribute to this issue.
can you please tell what is the best option to place the `d.ts` file.
**I think** I have two option :

1. contribute d.ts file in `definitelyTyped` repo
2. contribute d.ts file to `node-jose` repo 

I would like to follow the second option and could you please tell me how to achieve that. Could you please tell me best method to contribute typing file for a nodejs module?

**Comment by SimonSchick** [comment]
- DT generally won't argue so it's usually less _political_ when it comes to adding typings, just keep in mind DT tends to `lag` behind the actual package but it will usually be merged within a few days.
- Ideally the typings should be added *here* but that involves adding the `typescript` package to the build pipeline in order to test typings and as @linuxwolf said that involves developer overhead.

I'd suggest you add them to DT first since those will usually be accepted, once the DT typings are in place it's easy to create a pull request to move them here.

**Comment by nadunindunil** [comment]
Hi,
I finally managed to contribute to the defentelyTyped.
now you can find the type package from [https://www.npmjs.com/package/@types/node-jose](https://www.npmjs.com/package/@types/node-jose)
Thank you very much @SimonSchick for the support.
please let me know if you have any suggestions or problems.
❤️
