### ISSUE TITLE
why is aes-cbc-hmac-sha2 algorithm using loose HMAC verification on the JWE authentication tag?

### ISSUE THREAD

**Issue by emilesalem** [cisco/node-jose#136]
in line 282 of lib/algorithms/aes-cbc-hmac-sha2.js, a props object { loose : true} is passed to HMAC.verify

Why is that? 

Right now, JWE authentication tags can be the empty string and they'll still be passing the HMAC.verify.

I've added tests [here](https://github.com/emilesalem/node-jose/blob/issue/authentication-tag/test/algorithms/aes-cbc-hmac-sha2-test.js)  to show the problem.

**Comment by linuxwolf** [comment]
Strict requires the tag to be exactly the length HMAC-{size} returns.  However, aes-cbc-hmac-sha2 does not include the full HMAC value.

Not saying this isn't a problem that needs addressing; it should be using a "check over this length" instead of "check if some subset matches".

**Comment by linuxwolf** [comment]
Fixed in #137
