### ISSUE TITLE
Importing a webcrypto generated public key has no uses

### ISSUE THREAD

**Issue by LiraNuna** [cisco/node-jose#149]
Using webcrypto, I generated a an RSA-OAEP key with the following config:

```
{
    name: "RSA-OAEP",
    hash: "SHA-256",
    publicExponent: new Uint8Array([1, 0, 1]),
    modulusLength: 2048,
}
```

I then exported the key pair's public key using `jwk` and got:

```
{ alg: 'RSA-OAEP-256',
  e: 'AQAB',
  ext: true,
  key_ops: [ 'encrypt' ],
  kty: 'RSA',
  n: 'ukde4F1aQUv_MiOV4GcWmxMrMfzMHZQuw2BcUe0FE6cH1da9k0ac8-QFiT7IIxOXxkm4mMfgSZ2bxXNGOFBqzQ_FgXvl-ZMMPMKjutW7UmeoLzV-outKYQJ8gh8-3xDusHiXkYVh40-qJ0TME_bYA3nfI2vY5TFOlrV1QRkh-rQkH1qIkG9b6aQITXcC2Xp7uydwY4a1Dv7DWMai08hN55ojdcWP66bbEnA9vWnoLKhz3d76-M0RHOk5LDHW7qyMBAicUhvZMIuBoBQb6ndiRuBlFRITPodFHU3F2Sk-kf3a09WEtOCWWI7f5XrZ-0_Yjinbo03piOeUXWV5BYxg5Q'
}
```

Then trying to import this key as a JWK:

```
JWK.asKey(request.body.publicKey).then(x => console.log(x));
```

The result was a key that had no uses

```
JWKBaseKeyObject {
  keystore: JWKStore {},
  length: 2048,
  kty: 'RSA',
  kid: 'janf87ixKP5ZCFlw_N8LZ4PHojRDGdj-2hEZMHcOjbY',
  use: '',                                         // <-- missing uses
  alg: 'RSA-OAEP-256'
}
```

which means the key is useless and `encrypt` does not work.
I'm probably doing something wrong but I'm not sure what since the key is generated by webcrypto and does contain `key_ops: ['encrypt']`

**Comment by linuxwolf** [comment]
Did you actually try to use the key?  That result looks like a walk of the enumerable properties of a JWKBaseKeyObject instance.  The `use` property reports "" if it has not been set to anything.

**Comment by LiraNuna** [comment]
Yes, and I got an exception. When I traced the source of the exception, it was because `uses` did not have the correct usage, which lead me to this issue.

**Comment by linuxwolf** [comment]
Can you provide the error you got?  Would it also be possible to see a snippet of your failing code?

I tried the following with the key provided in the details above, and successfully created a JWE result:

```javascript
let key = { alg: 'RSA-OAEP-256',
  e: 'AQAB',
  ext: true,
  key_ops: [ 'encrypt' ],
  kty: 'RSA',
  n: 'ukde4F1aQUv_MiOV4GcWmxMrMfzMHZQuw2BcUe0FE6cH1da9k0ac8-QFiT7IIxOXxkm4mMfgSZ2bxXNGOFBqzQ_FgXvl-ZMMPMKjutW7UmeoLzV-outKYQJ8gh8-3xDusHiXkYVh40-qJ0TME_bYA3nfI2vY5TFOlrV1QRkh-rQkH1qIkG9b6aQITXcC2Xp7uydwY4a1Dv7DWMai08hN55ojdcWP66bbEnA9vWnoLKhz3d76-M0RHOk5LDHW7qyMBAicUhvZMIuBoBQb6ndiRuBlFRITPodFHU3F2Sk-kf3a09WEtOCWWI7f5XrZ-0_Yjinbo03piOeUXWV5BYxg5Q'
};
let plaintext = {
  sub: "somebody@nowhere.example",
  iss: "nowhere.example"
};

let jwe, failure;
jose.JWK.asKey(key).
       then((key) => jose.JWE.createEncrypt({ format: "compact"}, key).final(JSON.stringify(plaintext))).
       then((results) => { jwe = results; console.log(`SUCCESS: ${JSON.stringify(jwe)}`); }).
       catch((err) => { failure = err; console.log(`FAILED: ${err.message}`); });
```

**Comment by LiraNuna** [comment]
It's been a month since I last used this library and since this was a pretty big show stopper bug for us, we are using a different library. Therefor I do not have the error nor the code snippet that caused the original issue aside from what's in the original report.

Feel free to close this issue if you believe it's not a problem

**Comment by linuxwolf** [comment]
I do apologize for not responding sooner, and sorry that we could not accommodate you in a more timely manner.

Without more context into what the failure is, this does not appear to be an issue with this code.

**Comment by LiraNuna** [comment]
No problem, I'm sure the holiday season affected that. If I ever have the time to attempt to repro this again, I will open a new issue.
