### ISSUE TITLE
signing with HS384 and HS512 fails in basekey

### ISSUE THREAD

**Issue by phish108** [cisco/node-jose#150]
Hi 

I am currently working on a [helper script for signing and verifying JWT](https://github.com/phish108/node-jose-tools), when I ran into the following problem. 

```
jose.JWS.createSign(
               { fields: {alg: "HS512", typ:"JWT"}, 
                 format: "compact" }, 
               { key: mykey, 
                 reference: true})
        .update(JSON.stringify(payload))
        .final()
        .then((data) => process.stdout.write(data, "utf8"))
        .catch((err) => console.log(err)) ;
```

mykey is the following: 

```
{
  "kty":"oct",
  "kid":"foobar",
  "k":"-E_-rcOr6iesQ_BKO21DAuKdblhUmwciIx8Q6gUcUuG42Fw0zdPHPQtfZh19upvrh1Epevwz3Yc2a3YMGCJh1w"
}
```

(The key is generated with node-jose's own ```keystore.generate()```)

Everything is fine as long ```alg``` is "HS256". 

When I change ```alg``` to "HS384" or "HS512", then I receive the following error: 

```
Error: unsupported algorithm
    at JWKBaseKeyObject.value (node_modules\node-jose\lib\jwk\basekey.js:454:31)
```

I tried to understand the origin of the problem but I couldn't get my head around how ```octkey``` and ```basekey``` play together. This is how far I came: ```basekey``` expects the supported algorithms in the key's ```algorithms("sign")``` array, whereas ```octkey``` uses the class-wide constant ```SIG_ALGS``` for the supported algorithms. It appears that this constant is not used by the algorithms() method.

**Comment by panva** [comment]
I tried reproducing the issue with your code and didn't manage to do so. The following just works for me, all HS sign algs.

```js
const { JWK: { createKeyStore }, JWS: { createSign } } = require('node-jose');

(async () => {
  const ks = createKeyStore();
  await ks.add({
    kty: 'oct',
    kid: 'foobar',
    k: '-E_-rcOr6iesQ_BKO21DAuKdblhUmwciIx8Q6gUcUuG42Fw0zdPHPQtfZh19upvrh1Epevwz3Yc2a3YMGCJh1w',
  });

  const key = ks.get();

  for (const alg of ['HS256', 'HS384', 'HS512']) { // eslint-disable-line no-restricted-syntax
    const sig = await createSign({ // eslint-disable-line no-await-in-loop
      fields: {
        alg,
        typ: 'JWT',
      },
      format: 'compact',
    }, {
      key,
      reference: true,
    })
      .update(JSON.stringify({ foo: 'bar' }))
      .final();

    console.log(sig);
  }


})().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

What environment/versions are you running your code in?

**Comment by phish108** [comment]
@panva Thank you for the quick response. 

The environment is Win10 + node 8.9.3. 

Funny thing: The error disappeared here after I pushed my code to github. Sorry for the false alarm.

**Comment by julio899** [comment]
> I tried reproducing the issue with your code and didn't manage to do so. The following just works for me, all HS sign algs.
> 
> ```js
> const { JWK: { createKeyStore }, JWS: { createSign } } = require('node-jose');
> 
> (async () => {
>   const ks = createKeyStore();
>   await ks.add({
>     kty: 'oct',
>     kid: 'foobar',
>     k: '-E_-rcOr6iesQ_BKO21DAuKdblhUmwciIx8Q6gUcUuG42Fw0zdPHPQtfZh19upvrh1Epevwz3Yc2a3YMGCJh1w',
>   });
> 
>   const key = ks.get();
> 
>   for (const alg of ['HS256', 'HS384', 'HS512']) { // eslint-disable-line no-restricted-syntax
>     const sig = await createSign({ // eslint-disable-line no-await-in-loop
>       fields: {
>         alg,
>         typ: 'JWT',
>       },
>       format: 'compact',
>     }, {
>       key,
>       reference: true,
>     })
>       .update(JSON.stringify({ foo: 'bar' }))
>       .final();
> 
>     console.log(sig);
>   }
> 
> 
> })().catch((err) => {
>   console.error(err);
>   process.exit(1);
> });
> ```
> 
> What environment/versions are you running your code in?

first Thanks, and I have one question why in php no run JWT::decode example  i have this code

```php
<?php
use \Firebase\JWT\JWT;
$key = "secret";
if(isset($_REQUEST['JWT'])){
       print_r(    JWT::decode($_REQUEST['JWT'], $key, array('HS256'))  );
}
``` 
need add k parameter? -->  k: '-E_-rcOr6iesQ_BKO21DAuKdblhUmwciIx8Q6gUcUuG42Fw0zdPHPQtfZh19upvrh1Epevwz3Yc2a3YMGCJh1w',
