### ISSUE TITLE
cli tools (informative)

### ISSUE THREAD

**Issue by phish108** [cisco/node-jose#153]
Dear all

Thank you for node-jose!

I completed a cli toolkit under [node-jose-tools](/phish108/node-jose-tools) and pushed a release to npm.

It goes a bit beyond the cli-tool in the pull requests and supports the key features of node-jose:

* key and keystore management
* token signing and verification
* token encryption and decryption

Feedback, comments, and improvements are welcome.

**Comment by linuxwolf** [comment]
@phish108 Thanks for the head's up, and the work!  This works fairly well, and I'll submit any comments I have while using on your project.
