### ISSUE TITLE
Generating keys without a key store

### ISSUE THREAD

**Issue by buschtoens** [cisco/node-jose#158]
I understand that a vendor-provided dedicated key store structure is really useful in most applications. However, as far as I can see, pretty much all operations can be performed with the keys themselves, that is, without a `KeyStore`. The only thing you cannot do with public API only is generating a `Key` without creating a `KeyStore` to call `.create()` on first.

Also, even when importing a key "anonymously" with `jose.JWK.asKey` a unique `KeyStore` is implicitly created for the `Key`. Furthermore, a `Key` may not be created without a `KeyStore`:

https://github.com/cisco/node-jose/blob/2008bf46ee299d44d164c8a3147e65b5147384bb/lib/jwk/basekey.js#L39-L41

Why is that? I don't really see a reason, why a `Key` wouldn't be able to function without an associated `KeyStore`, but that is probably just my ignorance.

If there is indeed not real reason for tying `Key`s to a `KeyStore` would you accept a PR that makes using a `KeyStore` optional?

**Comment by linuxwolf** [comment]
When this project first started, `JWE.createDecrypt()` and `JWS.createVerify()` required a keystore.  There are still use cases where a keystore is useful.

Creating a key without any keystore would be a significant refactor, and I'm not sure it's worthwhile.  However, providing a way to create a key without requiring an explicit Keystore seems like a useful addition.

**Comment by buschtoens** [comment]
So in addition to `JWK.KeyStore#generate()`, there should be another static `JWK.generate()` (or `JWK.generateKey()`?) method, that is pretty much a hybrid of `KeyStore#generate()` and `KeyStore.asKey()`, i.e. generates a key with an implicit unique `KeyStore`.

I would consider completely factoring out the `keystore` property from the `Key` out of scope for now. This could be done in a follow-up PR.

**Comment by linuxwolf** [comment]
Release 1.0 added the static method `jose.JWK.createKey()`, which behaves as desired here (minus the complete removal of keystores).
