### ISSUE TITLE
Problem with HS256 and Key shorter than 256 bits

### ISSUE THREAD

**Issue by JMS-1** [cisco/node-jose#167]
Actually I think there is a reason for the comment // TODO: allow for HS{less-than-keysize} in line 134 of jwk/octkey.js but currently I don't get it. I'm using JWS with openid-client and a client_secret which is less than 256 bits and it get's no algorithm for verification. If I enforce HS256 in debug mode the following verification is fine.

Is there a standard specs to allow only key length with 256 or more bits?

**Comment by linuxwolf** [comment]
Per [JWA § 3.2](https://tools.ietf.org/html/rfc7518#section-3.2):

```
   A key of the same size as the hash output (for instance, 256 bits for
   "HS256") or larger MUST be used with this algorithm.  (This
   requirement is based on Section 5.3.4 (Security Effect of the HMAC
   Key) of NIST SP 800-117 [NIST.800-107], which states that the
   effective security strength is the minimum of the security strength
   of the key and two times the size of the internal hash value.)
```

IIRC, the `// TODO: ` was to work on implementing whatever less restrictive uses the JOSE WG were discussing, but they ended up not going there.

**Comment by JMS-1** [comment]
Thnx - then I'll have to talk to the provider :-(

Jochen
