### ISSUE TITLE
Question : Key format to decrypt JWE and verify JWS

### ISSUE THREAD

**Issue by robincher** [cisco/node-jose#169]
Hi folks,

Pardon my limited understanding , but would like to check how i can go about structuring the key input format during JWE decryption or JWS verifying.

For example, decrypting JWE using implied key

```
jose.JWE.createDecrypt(key).
        decrypt(input).
        then(function(result) {
          //  return result object
        });
```
Does that mean further hashing/encoding is required if i pass in the **key**'s value as a string , as shown below
```
key = '-----BEGIN RSA PRIVATE KEY-----
BASE64 ENCODED DATA
-----END RSA PRIVATE KEY-----`
```

Likewise for JWS, i am passing the key as 

```
key = `-----BEGIN PUBLIC KEY-----
BASE64 ENCODED DATA
-----BEGIN PUBLIC KEY-----
`
```

Thank you, and really appreciate you folks to have such a neat and handy JOSE's library.

**Comment by linuxwolf** [comment]
You need to convert the key string into an instance of jose.JWK.Key; `jose.JWK.asKey()` provides some convenience for that.

The JWE and JWS functions expect an instance of jose.JW.Key.  They take _**some**_ steps to coerce a JSON object into an instance of that class, but not any other types.  All other forms will need to be converted before passing them along to `jose.JWE.createDecrypt()` or `jose.JWS.createVerify()`.

The method [`jose.JWK.asKey()`](https://github.com/cisco/node-jose#importing-and-exporting-a-single-key) accepts two arguments:  the second informs what format the input is in.  For example, to input a PEM-encoded key:

```javascript
jose.JWK.asKey(key, "pem").then( (jwk) => key = jwk);
```

**Comment by robincher** [comment]
Cool, i will post an update here after i try later in the day.

Thanks for the quick response.

**Comment by robincher** [comment]
Hi @linuxwolf ,

Another quick question, this library only support compact serialization type for the input (to verify and decrypt)?

**Comment by linuxwolf** [comment]
This library supports all the serialization formats.  When encrypting/signing, the `compact` property in the `opts` argument to `createEncrypt()` or `createSign()` selects which serialization to output (one or `"compact"`, `"flattened"`, or `"general"`).  When decyrpting/verifying, it should properly detect the format.

**Comment by robincher** [comment]
Hi ,

I did the following as suggested , and still get an undefined error.

Do i need to create a keystore first?

```
         let key;  // How can i set this as an instance of  jose.JWK.Key ?
          jose.JWK.asKey(publicKey, "pem").
          then(function(result) {
           key = result;
           });
```

The string contents for publicKey is 

```
-----BEGIN CERTIFICATE-----
BASE64Encoded DATA ....
-----END CERTIFICATE-----
```

**Comment by phish108** [comment]
I recommend using a keystore and import the key using the keystore.add() function.
you find a working example [here](https://github.com/phish108/node-jose-tools/blob/master/lib/addkey.js) and [here](https://github.com/phish108/node-jose-tools/blob/master/lib/decrypt.js).

**Comment by linuxwolf** [comment]
Whether you use a keystore or `jose.JWK.asKey()`, the code exercised is the same.

@robincher some follow up questions:
* where are you encountering the `undefined` condition?
* does the key add/conversion fail (check by adding a callback for `catch()`ing)?
* what type of key is held by the certificate (RSA, DSA, ECDSA)?  Note that only RSA and ECDSA for NIST curves are supported

**Comment by robincher** [comment]
Hi @linuxwolf ,

I managed to get an instance of asKey() as suggested by you earlier.

Here are my code snippets 

```
 JOSE.JWK.asKey(publicKey, "pem").
                then((result) => {
                    return JOSE.JWS,createVerify(result).verify(input)
                    .then ((response)=> {
                        return response;
                    });
                }).catch((err) => {
                    throw new Error("JWS Verify Exception:" + err);
                }); 
```

Now the issue for me is ensure that the input matches what your library support.

Currently got a Unknown Message Digest error, probably cause my input is not adhering to the JWT set properly.

**Comment by linuxwolf** [comment]
I'm closing this issue; the original problem looks like it's been addressed.
