### ISSUE TITLE
algorithms: ['RS*'] option not working on JWS verification

### ISSUE THREAD

**Issue by JochenAtWork** [cisco/node-jose#173]
If you take a look in makeRE (utils/algconfig.js) it creates the pattern ^RS$ which is wrong - should be ^RS.\*$. 

In addition the push('.\*?') in the other if leave looks strange: shouldn't this be push('.\*')?

**Comment by JochenAtWork** [comment]
Hm, ['RS256'] aka 'RS256' doesn't work either.

**Comment by linuxwolf** [comment]
Thank you for the report.

There very clearly were some logic problems, and worse the tests weren't actually testing anything.  PR #174 should address them, and should be merged to master within the next day.
