### ISSUE TITLE
Error when preparing the recipient header

### ISSUE THREAD

**Issue by DonBrowny** [cisco/node-jose#175]
Hi,
I am using the JWK show below (RSA Key pair) to create a JWE and i am facing the index out of range on error on the line _joseTest\node_modules\node-jose\lib\jwe\encrypt.js:184:25_ as there is no alg attribute on the header array.
`{
    "kty": "RSA",
    "d": "--SOME VALUE--",
    "e": "AQAB",
    "use": "enc",
    "kid": "147386",
    "alg": "RS256",
    "n": "--SOME VALUE--"
  }`

On debugging i found that the error on the prepare the recipient header part using the baskey.js file as shown in the screenshot. The algs variable returned here is undefined.
![erroroccurance](https://user-images.githubusercontent.com/17572565/38970902-d7a8d9a4-43b5-11e8-9210-39686fa43fe1.png)

**Comment by linuxwolf** [comment]
The out of range error definitely should not be happening.  However, I think encrypt/decrypt would still fail (for a different reason) with that key: it's specifying `"alg": "RS256"` which valid for signing/verifying but not encrypting/decrypting.

In the future, please provide either a text snippet or the file/line number you suspect is the problem instead of pictures of code.  Pictures are more difficult to align with the rest of the code than a snippet or file/line number.

**Comment by linuxwolf** [comment]
In order to use an RSA key for JWE, use `"alg": "RSA-OAEP"` or `"alg": "RSA-OAEP-256"`.  `"alg": "HS256"` is only valid for JWS.

**Comment by DonBrowny** [comment]
Thanks..i was able to create the JWE with this one :smile:

**Comment by branfon1** [comment]
I am trying to implement the same functionality but in Angular, your help please

npm install node-jose

const jose = require('node-jose');
const b64u = require('base64url');

var $clave = '3ZZK5Q7CDQLV210642W7ZWXC6NB3IFQJ';

// create key.
jose.JWK.asKeyStore([
{
kid: $clave,
kty: 'oct',
k: b64u($clave)
}
]).then(ks => {

console.log('ks', ks)
// sign it
jose.JWS.createSign(
{
format: 'compact'
},
{
key: ks.get($clave),
header: {
alg: "HS256"
}
}
)
.update(JSON.stringify({ ppp: 12, ddd: 3883 }))
.final()
.then(sjwt => {
console.log(sjwt = ${sjwt});
// encrypt the signed message
jose.JWE.createEncrypt(
{
format: 'compact'
},
{
key: ks.get($clave),
header: {
alg: 'dir',
enc: 'A128CBC-HS256'
}
}
)
.update(sjwt)
.final()
.then(ejwt => {
console.log(ejwt = ${ejwt});
// decrypt the last message and failed in there.
jose.JWE.createDecrypt(ks.get($clave))
.decrypt(ejwt)
.then(djwt => {
console.log(JSON.stringify(djwt, null, ' '));
});
});
});
});

expected result :

![image](https://user-images.githubusercontent.com/56972159/122440787-87fa3b00-cf62-11eb-9ab2-f8eca83aba45.png)
