### ISSUE TITLE
Requiring es6-style modules breaks in web browser tests

### ISSUE THREAD

**Issue by linuxwolf** [cisco/node-jose#180]
Whenever a es6-style module is required, the web browser tests fail because functions aren't found.

The case-by-case hack being applied are:

```javascript
if (imported.default) {
    imported = imported.default;
}
```

These hacks are not sustainable.  Instead, changes to the configuration in karma/mocha/webpack is preferred.

**Comment by panva** [comment]
Closing this as the base64url dropin is no longer used, neither is the workaround.
