### ISSUE TITLE
A*GCMKW support

### ISSUE THREAD

**Issue by pratomchaip** [cisco/node-jose#190]
Hi there,

Are there any plans to introduce (back) support for A*GCMKW algorithm?

If not, would anyone know of any node packages that does support that algorithm?

Thanks.

**Comment by linuxwolf** [comment]
Hello @pratomchaip 

There are plans, and it should be in a release in the next month or so.  In fact, it should be supported on `master` now.

**Comment by pratomchaip** [comment]
Thanks @linuxwolf
