### ISSUE TITLE
JWK.createKey is not a function

### ISSUE THREAD

**Issue by eddielee6** [cisco/node-jose#192]
I'm trying to follow the docs to use the `JWK.createKey` function. But this does not appear to exist in the 0.11.1 latest release. Am I missing something?

**Comment by panva** [comment]
https://github.com/cisco/node-jose/tree/0.11.1

JWK.createKey is not released yet.

**Comment by linuxwolf** [comment]
Apologies, that was put into master in preparation for another "major minor" release, but a patch was required in the interim.  It is not yet available, but will be in the next release (hopefully early next week).

**Comment by eddielee6** [comment]
Ah okay no worries. Thanks for the quick reply.

**Comment by linuxwolf** [comment]
With release of 1.0, this should issue should be resolved.
