### ISSUE TITLE
Question about using PBES with direct content encryption

### ISSUE THREAD

**Issue by MaKleSoft** [cisco/node-jose#197]
So the spec describes using [password-based encryption for key wrapping](https://tools.ietf.org/html/rfc7518#section-4.8), but what about using PBES2 for content encryption directly, rather than using an intermediary key?

Here is what I would imagine the JWE to look like in that case:

```js
{
  "unprotected": {
    "alg": "dir",
    "enc": "PBES2-HS256+A256GCM",
    "p2s": "...",
    "p2c": ...
  }
  ...
}
```

Is this at all supported by the spec? Is there a reason why I wouldn't want to do this from a purely crypto perspective?

**Comment by linuxwolf** [comment]
There is no documented JWA algorithm for direct use of the PBES key.

**Comment by linuxwolf** [comment]
Closing this issue; with no such defined algorithm, there is nothing that can be done here.  It should be brought up on the jose@ietf.org mailing list.
