### ISSUE TITLE
[question] Prevent nextTick from being used when possible

### ISSUE THREAD

**Issue by panva** [cisco/node-jose#203]
Would you accept a change where this block was not applied in `node` environment? Or could we get rid of it altogether (seems forge has some resolved IE-related issues about setImmediate).

```js
// Prevent nextTick from being used when possible
if ("function" === typeof setImmediate) {
  forge.util.setImmediate = forge.util.nextTick = function(callback) {
    setImmediate(callback);
  };
}
```

I'm tracing a lot of eventloop blocks to node-jose and forge and started a fork where I remove all the browser specifics and convert to async syntax, wanted to see where forge is needed, etc. (that's how i found RS256 and the like don't use native crypto at all, see #202). I could not verify this is the cause of the loop blocks but it's definitely not pretty.

In my fork i plan to put the browser and forge fallbacks back in place once i have node coverage up to 100% and then open a pr with a webpack build in place.

**Comment by linuxwolf** [comment]
I think we can get rid of this altogether.  We can try it and see if SauceLabs squaks, at least.
