### ISSUE TITLE
Supported PEM Type not found

### ISSUE THREAD

**Issue by RezaErfani67** [cisco/node-jose#206]
```javascript
var keys= keypair();
JWK.asKey(keys.public,'pem').then(function(result){
console.log(result);        
})
```

this give error:
Supported PEM Type not found

i am using [keypair](https://www.npmjs.com/package/keypair)  to generate keys

**Comment by linuxwolf** [comment]
Thanks for the report.  It looks like `keypair` generates raw RSA keys and encodes them into ASN1 -> "RSA PUBLIC KEY" PEM.  This library does not yet support this raw key form; it only supports `spki`.
