### ISSUE TITLE
Misleading Error throw "no key found" when wrong key was found

### ISSUE THREAD

**Issue by andreassolberg** [cisco/node-jose#211]
I spent unneccesary much time debugging a error, where the wrong key was used.

The error thrown from verifying a JWS signature said `no key found`. In fact a non-empty keystore was provided, and it contained a key with the proper `kid` and the proper `alg`.

**Comment by linuxwolf** [comment]
My apologies for the delays in responding.

The `no key found` has turned into this library's generic error, and there is a major refactor effort underway that might better address this in the future.

If possible, could you provide what the expected `alg` was?
