### ISSUE TITLE
Parse and stringify js objects automatically to json

### ISSUE THREAD

**Issue by thomaschaaf** [cisco/node-jose#217]
Currently I have to manually parse and stringify the input. As seen here:

```
const jose = require('node-jose');

const input = { a: 'test' };

(async () => {
  keystore = jose.JWK.createKeyStore();
  key = await keystore.generate("oct", 256);

  result = await jose.JWE.createEncrypt({ format: 'compact' }, key)
    .update(JSON.stringify(input)).final();

  console.log(result);

  decrypted = await jose.JWE.createDecrypt(key).decrypt(result);
  console.log(JSON.parse(decrypted.payload));
})();
```

Would it be possible to automatically convert the js object into json and vice versa? Or am I missing how to call this function?

**Comment by panva** [comment]
The content of a JWS/JWE is not always JSON, there is a notion of `cty` - content-type inside a JWS/JWE but those are not always reliable and implementations are rather relaxed with their usage. We'll be sticking with requiring correct type to be passed in as well as not automagically parsing the payloads.
