### ISSUE TITLE
OperationError: 192-bit AES keys are not supported

### ISSUE THREAD

**Issue by mydata** [cisco/node-jose#220]
We are trying to decrypt a JWE object which has been encrypted by JWE algorithm as : ECDH-ES and Encryption algorithm as AES192 GCM with nimbus JOSE + JWT library. This logic is implemented by the java code - as part of a restful api implementation . We are are trying to decrypt that using node jose library with the following code:
jose.JWE.createDecrypt(key).
       decrypt(input).
       then(function(result) {
         // ....
       });
where private key is passed in JWK format, which resulted in OperationError: 192-bit AES keys are not supported. any suggestions what could be wrong? Is node-js library is not supported? Need - P 384 EC keys based decryption.

**Comment by phish108** [comment]
While I am not really working on the code myself, I scanned the code for your problem. 

It seems that AES192 GCM is not fully supported on platforms node-jose runs. I found references to Chrome not supporting 192-bit keys in the test files. I assume that this is the reason of the error you receive.

Moving to AES256 GCM might be an alternative, if you can control the other side of the API.

**Comment by panva** [comment]
Please select an algorithm that is cross-platform compatible. Ie implemented on your target audience environments.
