### ISSUE TITLE
No Key Found

### ISSUE THREAD

**Issue by cristianbravo** [cisco/node-jose#222]
Hi there! I've and idToken from AWS Cognito and the kid is: 
`{ kid: 'Olim3jgwhBm+r5Ur5nwHGhwqJZ6Nei+tC9jwFJzwS2I=',
  alg: 'RS256' }`

Then, from AWS service I search and get the JWS
`{ alg: 'RS256',
  e: 'AQAB',
  kid: 'Olim3jgwhBm+r5Ur5nwHGhwqJZ6Nei+tC9jwFJzwS2I=',
  kty: 'RSA',
  n: 'hsuMn6B9NVIOpWU7lEI4Tg1c0dv4w6QY0inz5uTqcpOi44iAmyQv8p4V2nyBbS_xHCpTx5Qal6HtBlKfRgQEelqWJoP1OjfqGqLpE5hu_uDdow_moXQHw2QY8BRrSAmXGzCX08I4iNgufB2avvm2FEOMbKAzwrqUzQaRmVJ5oG84XSNyS5POXV1jnE4vl7ZEHrbZqr780V0us0BjKNpwfdrMTbsduQ15yXVm8laf80axLGcb8rmhg8CUWz8ZoUeODm9gCRlxH6h-sMMKb9lmXz27985LknNUiSiX5aROTiUioY4Ynq1Ec2n_mquJyCo-ibbTXM2Rpm4wb8r6nnQTrw',
  use: 'sig' }`

So, when I try to verify with this code:
`jose.JWK.asKey(keys[keyIndex])
                    .then(function (result) {
                        console.log('Llave publica construida...');
                        console.log(result);

                        //verificar la firma
                        console.log('Intentando verificar la firma del token...');
                        return jose.JWS.createVerify(result).verify(idToken);
                    })`

I've this error
`Error: no key found`

When I builld the Key Object with `jose.JWK.asKey(keys[keyIndex])` I got:

`JWKBaseKeyObject {
  keystore: JWKStore {},
  length: 2048,
  kty: 'RSA',
  kid: 'Olim3jgwhBm+r5Ur5nwHGhwqJZ6Nei+tC9jwFJzwS2I=',
  use: 'sig',
  alg: 'RS256' }`

Please any guide.

**Comment by phish108** [comment]
Hi

The error you get is for now the default error message when the verification fails (see #211).

Without having a complete example, it is hard to tell, what is actually going wrong.

It seems that you work with a keystore, already. So why don't you pass the entire keystore to your verifier and let it perform the key selection for you?

Your code would then look like this: 

```
jose.JWK.asKeyStore({ keys })
    .then(
        function verifyWithKeystore(keystore) {
            return jose.JWS.createVerify(keystore).verify(idToken);
    })
    .then(
        function handleToken(token) {
            // find all relevant data in token.payload
    })
    .catch(
        function handleError(error) {
             // always get a "no key found" error :(
    });
``` 

I ran a variant of your code with the github version of [node-jose-tools](/phish108/node-jose-tools) without trouble. Therefore, I rule out a bug in node-jose.

My token is: 

```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdmVTBPSXQyS29UejhKSW02bmFxVnNieUdVczhtdGlNcl9rNUduTFBteEkifQ.eyJpc3MiOiJtZSIsImF1ZCI6InlvdSIsInN1YiI6Im1lIiwiaWF0IjoxNTM5MjcwNDQwfQ.LG4RN0M6Ez7rBx80mHqHZnWk7XhhwXtHfQLPXqcXxy3T1mejWRbGKm7JW0HKhYsJR2C8gw52lKuQ5Mupu9FJMtNtECmYl08A-erNyJu7m_uS7vu92WiEyZNNYz06X9YwRNCD3q2nPnNVsDitXqLURnZaXO0_jm_1YAsCTUkMPCgO3LeaPY-FQ58xWbivPmCHDFyQK0-Jxlpcd_nRpyHBqJhQD59jMXQVEAbAlGDZeD-HdI6bTzGD2hbVLm4tlasQ6gJhsbmH4xxdMm1bIcTyH3P6pi8mH1YQJyZbY8XVljYaPLeeV4wpa2aJxpf-p_A9L3av6lTHLdbNdJGFSJjQEQ
````

My key is: 

```
{
   "kty":"RSA",
   "kid":"gfU0OIt2KoTz8JIm6naqVsbyGUs8mtiMr_k5GnLPmxI",
   "e":"AQAB",
   "n":"nSumcZx-xHEXiLPrs0Aiwq3RE58q8ePwRHvJBqhhk8ojvra_hHIHhDTPcpve9RCyoR_uPa2ZSZyGx5OTACDuFsYWHE_lIuY-vHZKOzvbZ8XX1XqkR_pOEqS5UOqXpImWkWU45lgiNIUOdoXqqAzMSZGmGMHZ6xr8MoHwB0pKWIMy-Sm3AyIruGWqWfBtB3U4P3wJwO4lSKynQpL_l3A2QTxFK1gmSnaFGKrXx_19Qg6hmutkpa1dIec156NU6p41fV01b-nByAtaFJr2Y8cTE6CpM-p9TmowRHfpebQKA-AtC7D1VAAtvMX9F6C4ZZozTD7HgFlfycvvu81yVL6nhw",
   "alg": "RS256",
   "use": "sig"
}
```

My command is: 

```
echo TOKEN | jose verify -b -K 'KEY' 
```

You may replace the token and the key with your own data to verify that the source is ok.
