### ISSUE TITLE
crit members handling does not work as documented

### ISSUE THREAD

**Issue by phish108** [cisco/node-jose#223]
The README states for ```crit``` field member handling in verify and decrypt 

> To accept 'crit' field members, add the handlers member to the options Object. The handlers member is itself an Object, where its member names are the crit header member, and the value is one of:
> * Boolean: accepts (if true) -- or rejects (if false) -- the JWS if the member is present.

However, boolean values are ignore by the current code of JWE/decrypt.js and JWS/verify.js

**Comment by phish108** [comment]
Pull request #224 provided

**Comment by panva** [comment]
@phish108 will submit just a documentation change that removes the not implemented boolean way of using critical header members.
