### ISSUE TITLE
New release with performance improvements from master?

### ISSUE THREAD

**Issue by alexghr** [cisco/node-jose#225]
Hi,

This commit https://github.com/cisco/node-jose/commit/e25919b668cb276a78549541e0ae740f5fee3f73 that was merged into `master` a month ago brings massive performance improvements in my use case (and probably others as well :smile:). Do you plan on releasing it as a new version on npm?

**Comment by panva** [comment]
As soon as I get a hold of Matthew (he's occupied with conferences and workshops at the moment) to add me to npm i'll do a long overdue release.

**Comment by panva** [comment]
Resolved, node-jose@1.1.0
