### ISSUE TITLE
References to git make it impossible to build in a more restrictive environment

### ISSUE THREAD

**Issue by mojadev** [cisco/node-jose#226]
I would like to use node-jose in my company, which blocks direct references to github repositories. 
The following packages cause issues on the jenkins build as they reference github directly:

"node-forge": "https://github.com/linuxwolf/forge/archive/browserify.tar.gz",
"urlsafe-base64": "https://github.com/linuxwolf/urlsafe-base64/archive/encoding.tar.gz",

Is there a reason why these packages are referenced in github?

**Comment by panva** [comment]
This is no longer the case since version 0.9.4

**Comment by panva** [comment]
Np, would you mind closing the issue?
