### ISSUE TITLE
merge.js references incorrect file in comment header (minor)

### ISSUE THREAD

**Issue by patrickfav** [cisco/node-jose#228]
In file https://github.com/cisco/node-jose/blob/e25919b668cb276a78549541e0ae740f5fee3f73/lib/util/merge.js#L2 the file reference in the header is incorrectly 

    util/utf8.js - Implementation of UTF-8 Encoder/Decoder

should be something

     util/merge.js - Implementation of (...)

**Comment by panva** [comment]
Please submit a code comment pr.
