### ISSUE TITLE
add support for private keys with passphrase and cypher fields

### ISSUE THREAD

**Issue by davesag** [cisco/node-jose#234]
Node 10 introduced support for [`crypto.generateKeyPair`](https://nodejs.org/dist/latest-v10.x/docs/api/crypto.html#crypto_crypto_generatekeypair_type_options_callback) and the standard example includes a `cypher` and `passphrase` field.  However, according to other comments, [certificates with a passphrase are currently not supported](https://github.com/cisco/node-jose/issues/69#issuecomment-236133179).

This is therefore a feature request to support the `passphrase` option in `node-jose`.

Cheers

Dave

**Comment by panva** [comment]
unfortunately this won't be in our powers to deliver, in node >= 11.6 you may pass your encrypted keys to `crypto.createPrivateKey` with the passphrase and get a keyobject that you export as non-encrypted `pem` to pass to to `JWK.importKey`.

**Comment by davesag** [comment]
Can I take it then that this project is no longer being actively supported?

**Comment by panva** [comment]
> Can I take it then that this project is no longer being actively supported?

On the contrary, we do support the current API but in light of this being part of native node stable branch already don't feel like we need to have this in a package.

FWIW for environments other than node this feature doesn't make much sense anyway.

**Comment by davesag** [comment]
I think it’s rhen at least worth clarifying in the documentation that node-Jose is incompatible with pems that have passwords. Right now it just silently fails which is frustrating to debug.

**Comment by panva** [comment]
I agree. Thanks for pointing that out.
