### ISSUE TITLE
Cannot encrypt when JWK has alg set to dir

### ISSUE THREAD

**Issue by dswiecki** [cisco/node-jose#238]
Hi
I've got very similar problem to #151 
I am also trying to encrypt some data using JWE.createEncrypt with direct encryption with shared symetric key hence my JWK has `alg=dir` set.
Unfortunatelly when I use key like this I reveice error `Error: unsupported algorithm` on 
``` js
Object.defineProperty(this, "encrypt", {
    value: function value(alg, data, props) {
      // validate appropriateness
      if (this.algorithms("encrypt").indexOf(alg) === -1) {
        return Promise.reject(new Error("unsupported algorithm"));
      }
...
```
Neither setting the key encryption algorithm (alg) via a fields property nor enc does not help

However when I change `alg` on source jwkJson to corresponding `enc` everything works like a charm

```js
 async encryptSomeText() {
    const jwkJson = {"kty":"oct","kid":"99ee68dd-3ab8-4f1d-82ac-cf463021f873","alg":"dir","k":"53UjrjslXQdc82dMJUG8ORvpy_xB5lntDL2vhh_4heoXSXbQHNUXFmMlmF1zDyjtWHM_KIJjp5ejOVwsj5OfrA","enc":"A256CBC-HS512"}
    // jwkJson.alg = jwkJson.enc //this line fixes encryption
    const keystore = await jose.JWK.asKey(jwkJson).then(a => a.keystore)
    const key = keystore.get('99ee68dd-3ab8-4f1d-82ac-cf463021f873')
    const encryptedMessage = await this.encrypt("SOME TEXT", key)
    console.log(encryptedMessage)

    const decryptedMessage = await this.decrypt(encryptedMessage, keystore)
    console.log(decryptedMessage)
  }

  async decrypt(message, keystore) {
    return jose.JWE
      .createDecrypt(keystore)
      .decrypt(message)
      .then(decrypted => new TextDecoder().decode(decrypted.plaintext))
      .catch(() => message)
      .then(decrypted => decrypted)
  }

  async encrypt(text, key) {
    //return jose.JWE.createEncrypt({ format: 'compact', fields: {alg:'dir, enc:'A256CBC-HS512'} }, key)  
    return jose.JWE.createEncrypt({ format: 'compact' }, key)
      .update(text)
      .final()
  }
```

The issue I mentioned was closed but I think a bug is still there, here you have full JWK JSON

**Comment by daniloesk** [comment]
Since I bumped onto this as well, a word of advise: node-jose prints "unsupported algorithm" even when the problem is the key not being compatible with the algorithm.

For example, when encrypting with an octet key and alg dir you need a key with the exact bit length of the algorithm you want to use: 256 bits for A256GCM.

**Comment by daniloesk** [comment]
@dswiecki, setting alg to enc may work, but probably the result is not the one you would expect it to be.

**Comment by panva** [comment]
setting the key's alg to the enc value is actually exactly what you should do. See the [cookbook](https://tools.ietf.org/html/rfc7520#section-5.6) example

**Comment by branfon1** [comment]
I am trying to implement the same functionality but in Angular, your help please

npm install node-jose

const jose = require('node-jose');
const b64u = require('base64url');

var $clave = '3ZZK5Q7CDQLV210642W7ZWXC6NB3IFQJ';

// create key.
jose.JWK.asKeyStore([
  {
    kid: $clave,
    kty: 'oct',
    k: b64u($clave)
  }
]).then(ks => {

  console.log('ks', ks)
  // sign it
  jose.JWS.createSign(
    {
      format: 'compact'
    },
    {
      key: ks.get($clave),
      header: {
        alg: "HS256"
      }
    }
  )
    .update(JSON.stringify({ ppp: 12, ddd: 3883 }))
    .final()
    .then(sjwt => {
      console.log(`sjwt = ${sjwt}`);
      // encrypt the signed message
      jose.JWE.createEncrypt(
        {
          format: 'compact'
        },
        {
          key: ks.get($clave),
          header: {
            alg: 'dir',
            enc: 'A128CBC-HS256'
          }
        }
      )
        .update(sjwt)
        .final()
        .then(ejwt => {
          console.log(`ejwt = ${ejwt}`);
          // decrypt the last message and failed in there.
          jose.JWE.createDecrypt(ks.get($clave))
            .decrypt(ejwt)
            .then(djwt => {
              console.log(JSON.stringify(djwt, null, '    '));
            });
        });
    });
});


expected result :

![image](https://user-images.githubusercontent.com/56972159/122438494-64ce8c00-cf60-11eb-8dbf-e8fa0acdbaba.png)


https://stackblitz.com/
