### ISSUE TITLE
JWE with alg:dir enc:A128CBC-HS256

### ISSUE THREAD

**Issue by niwenhao** [cisco/node-jose#241]
Thanks for the excellent soft.
I have try encrypt and decrypt a JWEed message with alg:dir and enc:A128CBC-HS256.
I can encrypt it but failed in decrypt with a error of "mac check failed".
I could not find any testcase about encrypt and decrypt with alg:dir and enc:A128CBC-HS256.
Dose it exist?

**Comment by niwenhao** [comment]
To attach my code.

        const jose = require('node-jose');
        const b64u = require('base64url');

        jose.JWK.asKeyStore([{
            kid: 'mykey',
            kty: 'oct',
            k: b64u('ca06ba7343d14c21bad84602086a10a0')
        }]).then(ks => {
            jose.JWS.createSign({
                format: 'compact'
            }, {
                key: ks.get('mykey'),
                header: {
                    alg: "HS256"
                }
            }).update(JSON.stringify({ppp: 12, ddd: 3883}))
            .final().then(sjwt => {
                console.log(`sjwt = ${sjwt}`)
                jose.JWE.createEncrypt({
                    format: 'compact'
                }, {
                    key: ks.get('mykey'),
                    header: {
                        alg: 'dir',
                        enc: 'A128CBC-HS256'
                    }
                }).update(sjwt).final().then(ejwt => {
                    console.log(`ejwt = ${ejwt}`)
                    jose.JWE.createDecrypt(ks.get('mykey')).decrypt(ejwt).then(djwt => {
                        console.log(JSON.stringify(djwt, null, "    "))
                    })
                })
            });
        })

**Comment by mrkmrtns** [comment]
I had the same issue, I think You must specify 'alg' when You create key like this:

ose.JWK.asKeyStore([{
        kid: 'mykey',
        alg: 'A128CBC-HS256',
        kty: 'oct',
        k: b64u('ca06ba7343d14c21bad84602086a10a0')
    }])

Check if it helps...

**Comment by branfon1** [comment]
I am trying to implement the same functionality but in Angular, your help please

var $clave = '3ZZK5Q7CDQLV210642W7ZWXC6NB3IFQJ';

    // create key.
    jose.JWK.asKeyStore([
      {
        kid: $clave,
        kty: 'oct',
        k: b64u($clave)
      }
    ]).then(ks => {

      console.log('ks', ks)
      // sign it
      jose.JWS.createSign(
        {
          format: 'compact'
        },
        {
          key: ks.get($clave),
          header: {
            alg: "HS256"
          }
        }
      )
        .update(JSON.stringify({ ppp: 12, ddd: 3883 }))
        .final()
        .then(sjwt => {
          console.log(`sjwt = ${sjwt}`);
          // encrypt the signed message
          jose.JWE.createEncrypt(
            {
              format: 'compact'
            },
            {
              key: ks.get($clave),
              header: {
                alg: 'dir',
                enc: 'A128CBC-HS256'
              }
            }
          )
            .update(sjwt)
            .final()
            .then(ejwt => {
              console.log(`ejwt = ${ejwt}`);
              // decrypt the last message and failed in there.
              jose.JWE.createDecrypt(ks.get($clave))
                .decrypt(ejwt)
                .then(djwt => {
                  console.log(JSON.stringify(djwt, null, '    '));
                });
            });
        });
    });
    
    
    expected result :

![image](https://user-images.githubusercontent.com/56972159/122311195-43758d80-ced7-11eb-906c-140522d2efd6.png)
