### ISSUE TITLE
How to specify content encryption algorithm?

### ISSUE THREAD

**Issue by toodamax** [cisco/node-jose#251]
On previous versions, you can specify the content algorithm in `createEncrypt` function by setting `contentAlg` with the algorithm, for example `A126GCM`. How do you do that on version 1.1.0?

P.S. I'm using self-signed certificate. I import it thru `JWK.asKey` function.

**Comment by panva** [comment]
this would be the `alg` property of a JWE header, either per-recipient, protected, or unprotected depending on the used serialization and number of JWE recipients.
