### ISSUE TITLE
Error: no key found

### ISSUE THREAD

**Issue by Albertbol** [cisco/node-jose#262]
Hey,
 Using example from node-jose documentation, trying to decrypt payload with public key but receiving "Error: no key found"
```
const jose = require('node-jose')
	let key
	let enc
	let keystore
keystore = jose.JWK.createKeyStore()
const input = {
		'keys': [{
"kty": "RSA",
  "e": "AQAB",
  "use": "enc",
  "alg": "RS512",
  "n": "PUBLIC KEY IS HERE"
}]
}
```
	const textToDecrypt = 'some encrypted text'
```
jose.JWK.asKeyStore(input).then(function (result) {
			return keystore = result
		}).then(keystore => {
          jose.JWE.createDecrypt(keystore).decrypt(textToDecrypt).
then(function (result) {}).catch(e => {
console.log('Error: ', e)
})
})
```
// tried to return key and keystore and use it or using it from global variable allways same result
// Error: no key found 
// But code breaks on this line "jose.JWK.asKeyStore(input).then(function (result) "{ allways

**Comment by panva** [comment]
JWE encryption is "public key encryption", so you encrypt for the recipient with his public key and the recipient must decrypt using the private key. Decrypting with a public will fail and "no key found" is a generic message for not found key that would work to decrypt.

**Comment by Albertbol** [comment]
Please can you describe how to use key here in const input, because i tried already everything and private key also, here is the example which gives exactly the same error:
		'keys': [{
			'kty': 'RSA',
			'd': 'PRIVATE KEY'
		}]

**Comment by linuxwolf** [comment]
The private key requires all of the RSA fields (`d`, `e`, `p`, `q`, `dp`, `dq`, `qi`):
```
{
  "kty": "RSA",
  "e": "AQAB",
  "d": <PRIVATE KEY EXPONENT>,
  "p": ...,
  "q": ...,
  "dp": ...,
  "dq": ...,
  "qi": ...
}
```

I realize it's could be more convenient to only require `d` and `e`, however the underlying cryptographic implementations don't support that minimum well or at all.

**Comment by panva** [comment]
As an alternative, https://github.com/panva/jose Supports JWE and also calculating the missing private key optimization parameters.

**Comment by panva** [comment]
@linuxwolf if you would voice an opinion here https://twitter.com/_panva/status/1131493607301701632?s=21 we could have the source of these keys updated.

**Comment by Albertbol** [comment]
@linuxwolf i tried your option, but i dont have thoose parameters in my private key, so let it be '', and it didnt worked, do you mean i have to add thoose parameters some how?
Still same error no key found.

**Comment by panva** [comment]
Yes you have to provide a full JWK representation of the key including the optimization parameters. If you don’t have those or don’t know how to get them (i posted a library supporting calculating it above) request them from whomever issued the key.

**Comment by Albertbol** [comment]
Ok as i check out this example below:
```
const { JWK: { generateSync } } = require('@panva/jose')
const key = generateSync('RSA', 2048, { use: 'enc' })
// RSAKey {
//   kty: 'RSA',
//   private: true,
//   use: 'enc',
//   kid: [Getter],
//   e: [Getter],
//   n: [Getter],
//   d: [Getter],
//   p: [Getter],
//   q: [Getter],
//   dp: [Getter],
//   dq: [Getter],
//   qi: [Getter] }
```
Im getting just private key:
RSAKey {
  e: 'AQAB',
  kid: 'iKqbTF1gBcyzgl51zV5eDyEAbtfOv0Nw9e00jXrr0as',
  kty: 'RSA',
  n: 'oj0SseVsl_zQAH41gVcenTL14LEMrUHRBqtc3D5AZ5_a0t67628wGcKO27itQkInLuorUBalqKCkWgOVn53_4FtGlhfFT2MfvQCioJX39fWMI7eqykL3ZgZyT7Nz9qLLl2ezqYciq-eC0pLmz-uzjqY9wxtgVFBOiHyYJl1l9O9EGH5EJSSCWH981F7ZJOFU6Z7rMsxsAs3CteIAOLK97EV-Fen85BY7gVyRHbhk4dRHMmGCLC5UXkHb34AT75lEeEk1dXsW-HEy-LJyDjJRHOEUjtjqEbivAhOqV9fu_71XP5P7oRjn0JtVWfHyuqM7oFCZuhyf0cJADjbrbbamYw',
  use: 'enc'
}
But which dont have extra parameters, should i pass in i options commented parameters, but what is Getter its undefined?

**Comment by panva** [comment]
Why don’t you just do key.toJSON(true) as documented.

**Comment by Albertbol** [comment]
key.toJSON(true) worked thanks, but now when i try to use that generated private key in node-jose have "Error: key not valid for encrypting to recipient 0" error.
So i have private key with all of the lines:
```
var jose = require('node-jose')
	const keyPair = {
		keys: [
			{
				'e': 'AQAB',
				'n': 'public part',
				'd': 'private part',
				'p': '...',
				'q': '...',
				'dp': '...',
				'dq': '...',
				'qi': '...',
				'kty': 'RSA',
				'kid': 'mB7ih-T5bzeJIDUkhX1TCYibA5XgA6L_I0rvwCHmgus',
				'alg': 'RS512',
				'use': 'enc'
			}
		]
	}
//Declaring key store 
let keystore = jose.JWK.createKeyStore()
// Trying to encrypt dummy text
jose.JWK.asKeyStore(keyPair)
  .then(function (result) {
  // {result} is a jose.JWK.KeyStore
  keystore = result
  console.log('keystore', keystore)
  // console log looks like this "keystore JWKStore {}"
}).then(res => {
  let key = keystore.get('mB7ih-T5bzeJIDUkhX1TCYibA5XgA6L_I0rvwCHmgus', { use: 'enc' })
  console.log('getKey: ', key)
  // console log  get key looks like this :
/* getKey:  JWKBaseKeyObject {
  keystore: JWKStore {},
  length: 2048,
  kty: 'RSA',
  kid: 'mB7ih-T5bzeJIDUkhX1TCYibA5XgA6L_I0rvwCHmgus',
  use: 'enc',
  alg: 'RS512'
} */
return key
}).then(key => {
  const text = Buffer.from('Hey i need to be encrypted')
  jose.JWE.createEncrypt(key) // this line gives error Error: key not valid for encrypting to recipient 0
// tried key.toJSON(true) same result
        .update(text)
        .final()
        .then(function (result) {
	console.log(result)
	})
})
```
Thanks for helping me!

**Comment by webdevhu** [comment]
After consulting this [community forum post](https://community.developer.visa.com/t5/Implementation-API-Sample-Code/MLE-create-decrypt-no-key-found/td-p/21706), we realized our public and private keys were wrong, thus the "no key found" error. After fixing them, no error was thrown.
