### ISSUE TITLE
New point release for lodash vulnerability fix?

### ISSUE THREAD

**Issue by arvinsingla** [cisco/node-jose#272]
Hey folks, wondering if we could get a point release that includes the recent updates to dependencies including lodash (https://github.com/cisco/node-jose/pull/268)? The current version v1.1.3 is using a version of lodash which includes the following vulnerability (https://www.npmjs.com/advisories/1065). This makes our security team not happy.

**Comment by justaugustus** [comment]
Working on dependency updates here: https://github.com/cisco/node-jose/pull/342

**Comment by justaugustus** [comment]
@arvinsingla -- Can you try https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0 to see if that cleans some things up for you?

**Comment by justaugustus** [comment]
Closing this as the following packages are now available:

- Preferred: https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0
- Non-scoped previous package: https://www.npmjs.com/package/node-jose/v/2.1.0
