### ISSUE TITLE
unsecured JWS unsupported?

### ISSUE THREAD

**Issue by phish108** [cisco/node-jose#277]
I wonder if alg:none is unsupported for JWS? 

I know it is a border case, but since "none" is listed in RFC 7518, so I drilled into creating an unsecured JWS.

It tried different variations with and without keys and I always get "unsupported algorithm", which is also yielded if keys are also used with the wrong algorithm. 

I could not find a hint in the code that this (optional) part of RFC 7518 is implemented or not.

If alg:none is supported, how would I create an unsecured JWS?

**Comment by panva** [comment]
node-jose does not support unsecured JWS. 

If your runtime is Node.js try https://github.com/panva/jose i’ve recently added unsecured JWS support through a designated key object to, amonst others, prevent downgrade attacks and make “none” an entirely opt-in behaviour for both sign and verify

**Comment by phish108** [comment]
Thanks @panva this clarifies. 

I am currently working on having a more continuous update pipeline for node-jose-tools and test for the edge cases.  The key challenge is to know where the edges actually are :)
