### ISSUE TITLE
extending JWK.KeyStore

### ISSUE THREAD

**Issue by panva** [cisco/node-jose#29]
I was wondering what the motivation behind all constructor defined properties being unconfigurable is. I would like to write a decorator for the keystores used in my application which extends the KeyStore#get with functionality where if #get comes back empty it will try fetching the keys from a remote location (throttled jwks_uri refresh). However since the properties are not `configurable: true` i cannot do so.

**Comment by linuxwolf** [comment]
The main reason was to mitigate less-than-explicit leakage of cryptographic materials.  I was concerned about malicious code modifying the prototypes.

That said, I do want extension points -- just haven't gotten to them yet.  If the easiest (yet still relatively safe) is to allow some of the properties to be configurable, we can see about that.

**Comment by panva** [comment]
To start with it'd be helpful if the library returns it's own errors for when keys are not found or invalid, maybe something like KeyError with the regular message, that way i can at least watch for the rejected error name instead of "guessing" based on "key" presence in the message. I can prepare a PR with this, hopefully, non breakable change.
