### ISSUE TITLE
NPMJS Package.json dependencies mismatch with sourcode

### ISSUE THREAD

**Issue by danleegion** [cisco/node-jose#296]
I just realize http://registry.npmjs.org/node-jose/1.1.4 does not match with https://github.com/cisco/node-jose/blob/master/package.json

particularly node-forge version

**Comment by danleegion** [comment]
Hi,

Then i realize there was a commit https://github.com/cisco/node-jose/commit/277aab5c4c1c5b6b6c3923663d40aa9412f9f49d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2. Should the package version to be updated to 1.1.5?

**Comment by linuxwolf** [comment]
A new release is forthcoming, though it will be a bump in minor version (1.2.0) due to a change in supported platforms, triggered by updates from dependencies.

The oldest version of node.js supported will be v10, which matches the oldest version of node.js still supported.

**Comment by panva** [comment]
> though it will be a bump in minor version (1.2.0) due to a change in supported platforms

That would be a major semver bump then.
