### ISSUE TITLE
JWEDecrypter overwrites DEFAULT_OPTIONS with globalOpts argument

### ISSUE THREAD

**Issue by tunderdomb** [cisco/node-jose#312]
The `globalOpts` argument of `JWEDecrypter` is incorrectly handled in [lib/jwe/decrypt.js:39](https://github.com/cisco/node-jose/blob/master/lib/jwe/decrypt.js#L39).
The argument is directly merged with `DEFAULT_OPTIONS`.

```js
globalOpts = merge(DEFAULT_OPTIONS, globalOpts);
```

Every new instance overwrites `DEFAULT_OPTIONS`.
I assume the intent here was to create a new object with defaults overwritten by arguments, and not to overwrite the defaults.

**Comment by tunderdomb** [comment]
Provided a fix with a PR (#313).
Please consider releasing a new version with this fix, it affects all of our installations and blocks one of our business processes.
Thank you!

**Comment by fluffy** [comment]
Merged that - thank you
