### ISSUE TITLE
Dependency update request

### ISSUE THREAD

**Issue by ampliasec** [cisco/node-jose#329]
Dependency update request:

$ npm i node-jose
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

Thank you!.

**Comment by justaugustus** [comment]
Working on dependency updates here: https://github.com/cisco/node-jose/pull/342

**Comment by justaugustus** [comment]
All -- Can you try https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0 to see if that cleans some things up for you?

**Comment by justaugustus** [comment]
Closing this as the following packages are now available:

- Preferred: https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0
- Non-scoped previous package: https://www.npmjs.com/package/node-jose/v/2.1.0
