### ISSUE TITLE
Could you help remove the medium severity vulnerability node-forge in your package?

### ISSUE THREAD

**Issue by rampandu69701** [cisco/node-jose#331]
Hi ,@linuxwolf, @ragibkl, I’d like to report a vulnerability issue in node-jose-2.0.0:

**Issue Description:**
In node-jose-2.0.0, node-forge-0.10.0 library was detected as a vulnerability and I would like to ask you to upgrade it to node-forge-1.0.0 to fix the vulnerability. Are there any plans to release a new version with a fix for it?

Thanks,
Ram

**Comment by josser** [comment]
There is even a PR for this: https://github.com/cisco/node-jose/pull/332

**Comment by AndrewHarrison92** [comment]
Yeah, I ran into the issue through the passport-azure-ad library, and opened #332 
The tests are passing, but I really have no idea how robust those are.
Would appreciate if we could get this resolved @linuxwolf

**Comment by ferrohd** [comment]
If you're looking for a mantained library [this](https://www.npmjs.com/package/jose) seems like a good alternative. Quoting from its Readme:

> ### How is it different from node-jose?
> node-jose is built to work in any javascript runtime, to be able to do that it packs a lot of polyfills and javascript implementation code in the form of node-forge, this significantly increases the footprint of the modules with dependencies that either aren't ever used or have native implementation available in the runtime already, those are often times faster and more reliable.

**Comment by fluffy** [comment]
I'm not sure where the original people supporting this are but if someone would like to become a maintainer of this, please let me know by emailing me at fluffy@cisco.com (note I don't have much to do with this project but can help get someone permission)

**Comment by KTOmega** [comment]
I'm also experiencing problems due to this vuln, and having a new version of `node-jose` would be a huge help. @fluffy, would you happen to be able to contact anyone through internal channels that might be owners of this repo...? In case they don't check their GitHub accounts/emails.

**Comment by justaugustus** [comment]
Working on dependency updates here: https://github.com/cisco/node-jose/pull/342

**Comment by justaugustus** [comment]
All -- Can you try https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0 to see if that cleans some things up for you?

**Comment by KTOmega** [comment]
Thanks for helping out Stephen! Our package references `passport-azure-ad` which then references `node-jose`, so I'd need to send in a PR over to their team to use `@cisco-open/jose` and have them publish to get a fix on our end. Is there a chance we could publish to the perhaps older [`node-jose`](https://www.npmjs.com/package/node-jose) NPM package?

**Comment by justaugustus** [comment]
> Is there a chance we could publish to the perhaps older node-jose NPM package?

Yep, can work on this tomorrow!

**Comment by jasonnutter** [comment]
> > Is there a chance we could publish to the perhaps older node-jose NPM package?
> 
> Yep, can work on this tomorrow!

Much appreciated, thanks!

**Comment by justaugustus** [comment]
> Is there a chance we could publish to the perhaps older [`node-jose`](https://www.npmjs.com/package/node-jose) NPM package?

Cross-published as https://www.npmjs.com/package/node-jose/v/2.1.0.
Closing this out, but please report back if you run into any issues.

Thanks for your patience, everyone!
