### ISSUE TITLE
Need to update node-forge to latest version

### ISSUE THREAD

**Issue by Jaiminml** [cisco/node-jose#336]
We are getting security vulnerabilities due to older version of node-forge.

**Comment by fluffy** [comment]
Fixed

**Comment by Jaiminml** [comment]
When 2.0.1 version of node-jose will be available on https://www.npmjs.com/package .

**Comment by fluffy** [comment]
@justaugustus - can you help sort out a maintainer for this. I added you as maintainer for team that has commit to this

**Comment by justaugustus** [comment]
> @justaugustus - can you help sort out a maintainer for this. I added you as maintainer for team that has commit to this

Yep, I'll work on this!

**Comment by justaugustus** [comment]
Working on dependency updates here: https://github.com/cisco/node-jose/pull/342

**Comment by justaugustus** [comment]
Closing this as a duplicate of https://github.com/cisco/node-jose/issues/331.
Will continue the discussion there.

**Comment by justaugustus** [comment]
All -- Can you try https://www.npmjs.com/package/@cisco-open/jose/v/2.1.0 to see if that cleans some things up for you?
