### ISSUE TITLE
decrypt.js error: "no key found"

### ISSUE THREAD

**Issue by plusFeldt** [cisco/node-jose#391]
Calling decrypt with a private key works fine. Calling decrypt with a keystore (the private key is in) causes this error:

```
node_modules\node-jose\lib\jwe\decrypt.js:176
              reject(new Error("no key found"));
```

Demo code: https://gist.github.com/plusFeldt/69ff609ed757d298b3d0bb6d8642eb8b
What am I doing wrong?

**Comment by fbergeret95** [comment]
Bump this. I had similar code working just fine and now it's not

**Comment by fbergeret95** [comment]
Hi from the future. Came back just to say we found that the problem was not in the library but with our own private/public key pair.

If any reader is having this same issue, try testing your pair by encrypting and decrypting a simple payload to check if there are no problems on that end.

Cheers!
