### ISSUE TITLE
keyStore.generate() fails to keep generated key

### ISSUE THREAD

**Issue by fuzing** [cisco/node-jose#42]
The following code fragment:

var jose = require('node-jose');
var keyStore  = jose.JWK.createKeyStore();
keyStore.generate('oct', 256).then((key ) => {
    // result is a jose.JWK.Key
    console.log('got key', key);
}).catch((err) => {
    console.log('error', err);
});

generates something similar to the following object:
{ keystore: {},
  length: 256,
  kty: 'oct',
  kid: '5398e446-6cb2-4d03-b93f-c5bd4bfeb6ec',
  use: '',
  alg: '' }

(i.e. the resultant key should contain a 'k' element that is a Buffer consisting of [in this case] 32 bytes of random data).
The 'k' (key) element is generated during processing in octkey.js, but is dropped by the call to:
return new JWK.BaseKey(jwk.kty, self, jwk, cfg);
in keystore.js during the ".add".

**Comment by linuxwolf** [comment]
The secret/private key values are not exported unless specifically asked for.  In other words, the "k" member (when "kty" is "oct") is not enumerable.

However, it can be obtained by calling key.toJSON(true) or key.toObject(true).

**Comment by fuzing** [comment]
Mathew -
Wasn't clear from the documentation but that makes perfect sense.   Thanks for the quick reply.
Cheers, and have a nice evening.
