### ISSUE TITLE
Buffer._augment is not a function in Chrome

### ISSUE THREAD

**Issue by jean-moldovan** [cisco/node-jose#44]
Hi,
I'm using the [browserified version](https://github.com/jean-moldovan/node-jose-browserified) of node-jose in Chrome (47.0.2526.111 (64-bit)).

And when trying to encrypt:
```
Jose.JWE
          .createEncrypt({ format: 'compact' }, key)
          .update(Jose.util.asBuffer(input))
          .final();
```
I'm getting:
```
TypeError: Buffer._augment is not a function
```

**Comment by linuxwolf** [comment]
I'm not sure what is happening here.  The tests that run against Chrome/Firefox/Safari/IE/Edge all pass, and the function is defined.  Could there be an issue with how your bundle is created?

There should be a backlog item to stop using this method now that [Buffer](https://github.com/feross/buffer) supports more efficient creation around a Uint8Array.

**Comment by jean-moldovan** [comment]
Hm, looks like Buffer gets replaced by the browserify.

From browserify docs:
```
Additionally, if you use any of these variables, they will be defined in the bundled output in a browser-appropriate way: process, Buffer, global, __filename, __dirname
```

**Comment by linuxwolf** [comment]
Yes, and in order to have browser tests for node-jose, browserify is used to make those tests happen.

For an existence proof of it working in Chrome: [Manual Test Run](https://travis-ci.org/linuxwolf/node-jose/jobs/105446993)

**Comment by jean-moldovan** [comment]
Fixed this by downgrading to browserify v8.0.2, thanks.

**Comment by jean-moldovan** [comment]
I'll be updating [node-jose-browserified](https://github.com/jean-moldovan/node-jose-browserified) soon :smile:

**Comment by jean-moldovan** [comment]
One more thing,
