### ISSUE TITLE
Plans to support HS512 algorithm

### ISSUE THREAD

**Issue by charandas** [cisco/node-jose#47]
Are there any plans to support HS512 algorithm?

**Comment by linuxwolf** [comment]
[HS512 is already supported](https://github.com/cisco/node-jose/blob/master/test/algorithms/hmac-test.js).  Are you seeing problems on a particular platform?

**Comment by charandas** [comment]
Thanks @linuxwolf for the prompt reply.

I am on OS X, when using  the below HS512 jwk, `asKeyStore` throws.
```js
var JWK = {
	store: require("node-jose/lib/jwk/keystore.js")
};
var jwks =  {
		"keys": [{
			"kty": "oct",
			"use": "enc",
			"kid": "78f23b2c-7f9d-46df-9a3d-722421af8af8",
			"k": "mJJG0IycnTFF0gjcljU_rl4va0sp_KO3zZWZNLwcbf20Ixt5DeRwS3NvxJFAFY4xItzSRBUDq1FO_nPJb4QzMmi93oQD_58jy19hRhNPv5XODd4i1EcPn_cp7D8Y4x0T9UsszpFWumtV2tgSZoOu2W6NWMX2Ptt-QrXLO-u1ECvP-d-SeSforf4ysWPb5QlYJHcYjADo-YEKu64BxGtEbI7U0jlXoU_d06a8o1YddF1DLOzVam9VPdGjB1uT139URgYv-r-bBTGskiUcdKkPMjXRJur31p_cPnjQUG2ZaeY-OnLhPtCPjqUF9uZxkrGY8xYyCYJv4U1RjpdEa-hc1g",
			"alg": "dir"
		}, {
			"kty": "oct",
			"use": "sig",
			"kid": "349e81ec-698b-40be-bbbb-d8b65bddc076",
			"k": "ow4S7bB57wNZixw1VvO56qMA8MF4SjNQVpCbZPTAuDYrH5FMFjSgw-Ul3IvG5C39i0Yn7sxM3swr01OcI0qBqHpTQ3GNR6DEdPlXp6cftR5Lz0SX6NioHHqvR88gaVRIBizGjplex3DeKYrI3WTyH2feFYfuL16j3R6vxS2JDQ86Tp5a4mivy_Vm-NTtpdFyj3hKbhabQcMz2iL8RujS-C3i918qgVXJ1WdZ-ltgPN7PbxQzwHEkPXiqvlZYz_Eqk10moIrF-nUUEwhQsv3-QstlR1UkgZPR2-gatgbXg3XWhSl7HJXxmuRuBOQUTthmO3cuIn0u3QK85roy7yIMKQ",
			"alg": "HS512"
		}]
	};
JWK.store.KeyStore.asKeyStore(jwks) // throws  [Error: unsupported key type]
```

**Comment by linuxwolf** [comment]
Requiring the specific "keystore.js" file rather than `require("node-jose")` will certainly cause this problem, and it's not a supported usage pattern.

Is there a particular reason you can't simply include `require("node-jose")` ?

**Comment by charandas** [comment]
I see. I got that from tests. At first, I was doing, but the `keystore` kept coming out to be `{}`, so I tried to adapt my code as close to tests.
```
var jose = require('node-jose');

jose.JWK.asKeyStore(response.jwks)
		 .then(function(result) {
			keystore = result;
			assert.ok(jose.JWK.isKeyStore(keystore));
			console.log(keystore); // => gives {}
		 })
```

Can you please explain why the `keystone` is empty? I wanna export this key as a cert (pem) and not sure how to go about it.

**Comment by linuxwolf** [comment]
We need to provide some independent examples.  The tests are written to test behaviors in isolation most of the time, and the README.md does have snippets of doing most things in node-jose.  However, it would help to have something runnable/hackable you can start with.

What you can do is call `keystore.get(kid)` if you have a specific key you're looking for, or `keystore.all()` to get an array of all keys in the keystore.  `.get()` returns a single jose.JWK.Key, while `.all()` returns an array of jose.JWK.Key instances.

From there, you can call `key.toPEM()` to get the PEM-encoded raw key format.  However, today DER and PEM are only supported for RSA and EC keys -- not symmetric keys.  Also, it returns the "raw" key, not a certificate.

**Comment by charandas** [comment]
Thanks. I will close this for now, as HMAC is supported very well. :+1:
