### ISSUE TITLE
JWS decrypt with wrong recipient key rejects with 'no key found'

### ISSUE THREAD

**Issue by skoni** [cisco/node-jose#49]
If there is an error during the algorithm unwrap promise in decrypt, it will not lead to rejection of the decryption promise. `processKey` gets passed as the promise error handler. I don't understand if the intention here was to recursively call `processKey` until one key succeeds. Or if it was to run it only once, then `reject` should be passed as error handler in then of the algPromise here:

https://github.com/cisco/node-jose/blob/master/lib/jwe/decrypt.js#L118-L127

The problem is, that errors will not get passed on to the user, e.g. when a recipients keys alg is wrong it will reject with "no key found", because `processKey` will run out of recipients and swallow errors.

**Comment by linuxwolf** [comment]
The original intent was to continue processing the loop if there were multiple recipients.

Special handling of the single-key case is certainly possible, and we can look into dealing with that better.  We're also very open to PRs that improve this logic.

**Comment by skoni** [comment]
Thanks for the answer. I'll see if i can add the error reporting.

**Comment by Vishal8523** [comment]
@tillre : Request you to share the fix done from your end.

**Comment by Vishal8523** [comment]
@linuxwolf : Request you to share the fix done from your end. Your help appreciated.
