### ISSUE TITLE
Enhancement Suggestion: Add key to JWS.verify result

### ISSUE THREAD

**Issue by msamblanet** [cisco/node-jose#5]
In some cases, the application verifying the signature of a JWS may want to know which key was used to perform the verification - perhaps there are multiple valid signers and it wishes to know which one signed it.

The JWA.decrypt method already returns the key - adding a similar attribute on the result from verify method would allow for this.

I can volunteer to create a PR if needed (although it may be a little bit till I can get to it)

**Comment by linuxwolf** [comment]
This makes sense.  Not sure when I would get to it myself, though ... PRs are welcome!
