### ISSUE TITLE
typo lib/algorigthms/constants.js

### ISSUE THREAD

**Issue by martinfridrich** [cisco/node-jose#62]
Hi,

in file `lib/algorithms/constants.js` line 39 is probably typo in algorithm name `ECDH-EC+A256KW`(based on `RFC 7518` should be `ECDH-ES+A256KW`). 
Program crash with error `invalid key length` If you use key with `"alg": "ECDH-EC+A256KW"` for `JWE.createEncrypt(...)....`

**Comment by linuxwolf** [comment]
Good catch.  Thought we had tests for this, but we don't.  Will have to add them soon, but for now a fix with the typo correction is enough.
