### ISSUE TITLE
Allow passing of a JWS into jose.JWS.createVerify()

### ISSUE THREAD

**Issue by bifurcation** [cisco/node-jose#65]
Many times, I just want to know that a JWS verifies using the JWK in its "jwk" parameter.  `jose.JWS.createVerify()` should be able to take a JWS and populate any "jwk" headers it finds into its keystore.

**Comment by linuxwolf** [comment]
Instead of doing this on `createVerify()`, what if it used keys it found while processing in `verify()`?  It seems to me that the ultimate goal is met, without substantially changing node-jose's flow.

**Comment by bifurcation** [comment]
That would work for me.
