### ISSUE TITLE
How to add custom adata for decryption?

### ISSUE THREAD

**Issue by geocine** [cisco/node-jose#75]
This is the original code inside decrypt.js

```
var adata = input.protected;
if ("aad" in input && null != input.aad) {
  adata += "." + input.aad;
}

var params = {
  iv: jwe.iv,
  adata: adata, // I want to add additional stuff here like + "something.something"
  tag: jwe.tag,
  kdata: kdata,
  epu: jwe.epu,
  epv: jwe.epv
};
```

I wanted to add something on the **adata** , because I am adding stuff on **adata** during the encryption process from my .NET token provider.

**Comment by linuxwolf** [comment]
As implied by [RFC 7516](https://tools.ietf.org/html/rfc7516#section-7.2), the `aad` is carried only in one of the JSON serializations as the `aad` member of the top-level object:

```json
{
      "protected": "eyJhbGciOiJ...4R0NNIn0",
      "encrypted_key": "4YiiQ_ZzH76TaIkJmYfRFgOV9MIpnx4X",
      "aad": "WyJ2Y2FyZCIsW1sidmVyc2...Ik0iXV1d",
      "iv": "veCx9ece2orS7c_N",
      "ciphertext": "Z_3cbr0k3bVM6N3oSNm...CZTpbQAkFV",
      "tag": "vOaH_Rajnpy_3hOtqvZHRA"
}
```
`node-jose` can decrypt this format.

You can see a complete example of a JSON serialization with the additional data in the [cookbook](https://github.com/ietf-jose/cookbook/blob/master/jwe/5_10.including_additional_authentication_data.json).

**Comment by geocine** [comment]
So I realized there is something wrong with our encryption because we don't include this on the serializations. However on the decrypt.js looks like aad is not being checked or am I missing something?

```
      if (typeof input === "string") {
        input = input.split(".");
        input = {
          protected: input[0],
          recipients: [
            {
              encrypted_key: input[1]
            }
          ],
          iv: input[2],
          ciphertext: input[3],
          tag: input[4]
        };
      } else if (!input || typeof input !== "object") {
        throw new Error("invalid input");
      }
```

**Comment by linuxwolf** [comment]
That snippet is normalizing the input from the (string) compact serialization into a JSON serialization.  There's no need to explicitly check for `aad` there.

**Comment by geocine** [comment]
Thank you, I will check your encryption implementation. We are utilizing the `aad` but in an incorrect way so I have to do this hack on your library.

**Comment by geocine** [comment]
@linuxwolf  thanks I got it now, I just realized that I could use the flattened JSON serialization as input.  I thought it only supports the (string) compact serialization as input.

**Comment by linuxwolf** [comment]
We tried hard to support all the serializations! (-:
