### ISSUE TITLE
Does node-jose support RSA-OAEP-256 key encryption algorithm?

### ISSUE THREAD

**Issue by ygc16** [cisco/node-jose#76]
Hi,

Does _node-jose_ support `RSA-OAEP-256` key encryption algorithm?

When debugging why a test is failing, we found out that the root cause of the problem is this error:

    Invalid RSAES-OAEP padding.

**NOTE:** The JWE payload we are trying to decrypt is produced by a Java app that has Oracle's _Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files_.

Thanks in advance,
Jacob.

**Comment by linuxwolf** [comment]
It does support `RSA-OEAP-256`.

Is it possible that the library you're using did not use SHA-256 for both the hash and MGF?  This was a concern found in an earlier round of interop -- apparently some libraries will still use SHA-1 for the MGF even if SHA-256 is set for the hash.

**Comment by ygc16** [comment]
Hi @linuxwolf,

One more question: is `AES-256` supported too?

Thanks,
Jacob

**Comment by ygc16** [comment]
Hi,

The content we are trying to decrypt looks like this:

```json
{
  "protected": "...",
  "unprotected": {},
  "recipients": [
    {
      "header": {
        "kid": "my-key-id",
        "alg": "RSA-OAEP-256"
      },
      "encrypted_key": "..."
    }
  ],
  "iv": "...",
  "ciphertext": "...",
  "tag": "..."
}
```

And it is encrypted with an RSA 2048 (RSA-256-OAEP) KEK (key encryption key) and AES/256/GCM/NoPadding for CEK (content encryption key).

We import the private key using code that is similar to this:

```javascript
var privateKey = fs.readFileSync('./test/spec/my-key-id.prv.der');
keyStore.add(privateKey, 'pkcs8');
```

And then decrypt the JWE payload using:

```javascript
jose.JWE.createDecrypt(keyStore).decrypt(theJsonWebEncryptionStr);
```

Which throws the aforementioned key not found error.

It is not obvious how we can:

* Set the KID for the loaded private key
* Set the content encryption algorithm (`AES/256/GCM/NoPadding`)

Do you have any examples showing how these two tasks can be done?

Thanks,
Jacob.

**Comment by linuxwolf** [comment]
Various modes of `AES-256` are supported (`A256CBC-HS512` and `A256GCM` for content encryption).

The `key not found` error is the overly generic error node-jose returns when decryption fails.  It's something that needs to be addressed, but it's not clear what the best way to do that is.

In your example, you can set the KID by passing an Object as the last argument:

```
keyStore.add(privateKey, 'pkcs8', { kid: keyId });
```

Also, you can simply pass the expected (jose.JWK.KeyObject) key to `createDecrypt()`:

```
jose.JWE.createDecrypt(privateKeyObj).decrypt(theJsonWebEncryptonStr);
```

Given how you are describing the algorithms in use, it appears you are also using Java.  Are you sure that the OAEP-Padding in use is really using `SHA-256` for both the hash and the MGF?  If I recall earlier findings correctly, simply providing the string descriptors to JSSE only changes the hash while the MGF is still `SHA-1`.  I don't recall what it takes to change the MGF in Java, but I know it's possible.

**Comment by linuxwolf** [comment]
Also, when passing a `String` to `JWE.Decrypter.decrypt()`, that string is assumed to be the compact serialization.  If you really are using the JSON general serialization, be sure to pass it to `decrypt()` as a parsed JSON object (e.g., `JSON.parse()`).
