### ISSUE TITLE
JWE generation 

### ISSUE THREAD

**Issue by parisbutterfield** [cisco/node-jose#78]
I'm having an issue when generating keys and encrypting/decrypting JWE tokens.

The code I use to generate a key:

`var props = {
  kid: 'gBdaS-G8RLax2qgObTD94w',
   alg: 'ECDH-ES',
   enc: 'A128CBC-HS256'  
};
var key = keystore.generate("EC", "P-256", props).
        then(function(result) {
            return result;
}); 
`
The exported keystore looks like:
{"keys":[{"kty":"EC","kid":"gBdaS-G8RLax2qgObTD94w","alg":"ECDH-ES","crv":"P-256","x":"_CIf7CLE6by9KPhfh2Ht6QiWQUtKnLn63_RwMiR6xpM","y":"LHZv_ZQFW0T6ETJpLReWVwhAda5gEu_smsMcLpE3HAs","d":"BbjYz_SE54f8RdSmPQyrCBYDZwQu9ElKc5yo9ncIg84","enc":"A128CBC-HS256"}]}

I can generate a JWE using the following code:
` jose.JWE.createEncrypt({ format: 'compact' }, keystore.get('gBdaS-G8RLax2qgObTD94w')).
        update(jose.util.asBuffer(JSON.stringify(input))).
        final(). `

The resulting JWE is as follows:
eyJhbGciOiJFQ0RILUVTIiwia2lkIjoiZ0JkYVMtRzhSTGF4MnFnT2JURDk0dyIsImVwayI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6IlM0R2dkakZPOW05c0htRmg0aWM3RU00eldRN29saHpCMDhOVkZzNmptaVkiLCJ5IjoiaE5oY0txSVJLVVMxTFA5RFZmY244eHN0Njl0ZUdWbHpaMExwS0U2OXhHTSJ9LCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..9qHFZOcLInDTwnRqziyAWA.X5-iISesuGg2wZuJpibdc1ppCUgo8BlsCh-Xs7BHy4o.qB-dljypQAMCdu1QNjGo-g

When I try to decrypt the token I get the following error:

[Error: no key found]

Based off the unit tests I've looked through (jwe-test.js). When you use the [cookbook](https://github.com/ietf-jose/cookbook/blob/master/jwe/5_7.key_wrap_using_aes-gcm_keywrap_with_aes-cbc-hmac-sha2.json) the structure of the key is different. I notice there's an "encrypting_content" section. I've tried a few different combinations to create a key but haven't had any success. Can someone provide an example on how to generate keys?

**Comment by linuxwolf** [comment]
The key you generated is correct.  The cookbook JSON files are broken out to follow the flow of [RFC 7520](https://tools.ietf.org/html/rfc7520), and not wholly created using `jose.JWK.generate()`.

I was able to decrypt your JWE to `{"user":"10155129962707119"}` using your key, with the following:

```javascript
let p, keystore, jwe;

jwe = 'eyJhbGciOiJFQ0RILUVTIiwia2lkIjoiZ0JkYVMtRzhSTGF4MnFnT2JURDk0dyIsImVwayI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6IlM0R2dkakZPOW05c0htRmg0aWM3RU00eldRN29saHpCMDhOVkZzNmptaVkiLCJ5IjoiaE5oY0txSVJLVVMxTFA5RFZmY244eHN0Njl0ZUdWbHpaMExwS0U2OXhHTSJ9LCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..9qHFZOcLInDTwnRqziyAWA.X5-iISesuGg2wZuJpibdc1ppCUgo8BlsCh-Xs7BHy4o.qB-dljypQAMCdu1QNjGo-g';

p = jose.JWK.asKeyStore(keystore);
p = p.then((r) => keystore = r);
p = p.then(() => jose.JWE.createDecrypt(keystore).decrypt(jwe))
p = p.then(r => jwe = r);
```

Without seeing your decryption code, I'm not sure what the problem is.  Is it possible that the keystore your decryption code has does not include the key you generated?

**Comment by linuxwolf** [comment]
Looking at your comment more, I wonder if you're not using promises correctly.

For example, the following:

```javascript
var props = { kid: 'gBdaS-G8RLax2qgObTD94w', alg: 'ECDH-ES', enc: 'A128CBC-HS256' };
var key = keystore.generate("EC", "P-256", props). then(function(result) { return result; });
```

The value of `key` is a Promise, **not** a `jose.JWK.Key`.

**Comment by parisbutterfield** [comment]
:) When decrypting  I was using ` decrypt(jose.util.asBuffer(req.query.token))
`
when I should've been a plain string. Using  `decrypt(req.query.token)` works fine. I guess I got confused because when creating a JWE the input has to be a buffer. Thanks for your help.
