### ISSUE TITLE
Why github tar.gz dependency

### ISSUE THREAD

**Issue by mdunisch** [cisco/node-jose#96]
Hi,

why you use depencies with a github-url and and tar.gz file?

I wounder why you don't use a normal npm package dependeny?

**Comment by mdunisch** [comment]
@linuxwolf 
there are still tar.gz dependencies: 
"node-forge": "https://github.com/linuxwolf/forge/archive/browserify.tar.gz"

**Comment by panva** [comment]
I assume this was automerged by github due to my commit message. @linuxwolf should reopen.

**Comment by linuxwolf** [comment]
Finishing some fuzz testing on the other PR.  Please have some patience.

**Comment by panva** [comment]
@linuxwolf this is great!
